// This file is auto-generated by scripts/build-dictionary.mjs
// Do not edit this file directly.

export interface DictionaryEntry {
  term: string;
  meaning: string;
}

export const militaryDictionary: DictionaryEntry[] = [
  {
    "term": "(1) ADMINISTRATION/LEGAL SERVICES SCHOOL",
    "meaning": "Admini/LegsvcScol"
  },
  {
    "term": "ADALCON",
    "meaning": "Advise all concerned."
  },
  {
    "term": "ADDU",
    "meaning": "Additional duty."
  },
  {
    "term": "ADLVADDR",
    "meaning": "You are directed to keep the CMC advised of an address at which you can be reached by telegram at all times while in a proceed, travel, or leave status."
  },
  {
    "term": "ADMSG",
    "meaning": "Please advise by message."
  },
  {
    "term": "ADP",
    "meaning": "Aeronautically Designated Personnel."
  },
  {
    "term": "ADTAKE",
    "meaning": "Please advise action taken."
  },
  {
    "term": "AIR BASE",
    "meaning": "AB"
  },
  {
    "term": "AIR SUPPORT RADAR TEAM",
    "meaning": "ASRT"
  },
  {
    "term": "AIR/NAVAL GUNFIRE LIAISON COMPANY",
    "meaning": "ANGLICO"
  },
  {
    "term": "ALCOM",
    "meaning": "All commands."
  },
  {
    "term": "ALCON",
    "meaning": "All concerned."
  },
  {
    "term": "ALMAR",
    "meaning": "All Marine Corps activities."
  },
  {
    "term": "AMPHIBIOUS RECONNAISSANCE TEAM",
    "meaning": "ART"
  },
  {
    "term": "AMPHIBIOUS RECONNAISSANCE UNIT",
    "meaning": "ARU"
  },
  {
    "term": "AMPHIBIOUS SQUADRON",
    "meaning": "PHIBRON"
  },
  {
    "term": "AMPHIBIOUS WARFARE SCHOOL",
    "meaning": "AWS"
  },
  {
    "term": "APOD",
    "meaning": "Aerial port of debarkation"
  },
  {
    "term": "APOE",
    "meaning": "Aerial port of embarkation"
  },
  {
    "term": "ARMED FORCES STAFF COLLEGE",
    "meaning": "AFSC"
  },
  {
    "term": "ARMORED VEHICLE LAUNCHED BRIDGE",
    "meaning": "AVLB"
  },
  {
    "term": "ARMY OF THE U.S.",
    "meaning": "AUS"
  },
  {
    "term": "ARMY SECURITY AGENCY",
    "meaning": "ASA"
  },
  {
    "term": "ARPROREP",
    "meaning": "Upon arrival further proceed and report (to)."
  },
  {
    "term": "ARREP",
    "meaning": "Upon arrival report (to) ."
  },
  {
    "term": "ARREPCOVES",
    "meaning": "Upon arrival report to the commanding officer of that vessel for duty."
  },
  {
    "term": "AUTHDELREP",
    "meaning": "With authority to delay in reporting until (date)."
  },
  {
    "term": "AUTHPROBOUT",
    "meaning": "Authorized to proceed on or about (date)."
  },
  {
    "term": "AVNCM",
    "meaning": "Assigned to duty involving regular and frequent flights as a crewmember."
  },
  {
    "term": "AVNOTCM",
    "meaning": "Assigned to duty involving regular and frequent flights as a non-crewmember."
  },
  {
    "term": "BAGAIR",
    "meaning": "While traveling via air outside the United States (number of pounds indicate) baggage to accompany is authorized."
  },
  {
    "term": "BATTALION",
    "meaning": "Bn"
  },
  {
    "term": "BATTALION LANDING TEAM",
    "meaning": "BLT"
  },
  {
    "term": "BATTERY",
    "meaning": "Btry"
  },
  {
    "term": "BLOUNT ISLAND COMMAND",
    "meaning": "BICMD"
  },
  {
    "term": "BRIGADE",
    "meaning": "Bde"
  },
  {
    "term": "BRIGADE SERVICE SUPPORT GROUP",
    "meaning": "BSSG"
  },
  {
    "term": "BUREAU OF MEDICINE AND SURGERY",
    "meaning": "BUMED"
  },
  {
    "term": "BUREAU OF NAVAL PERSONNEL",
    "meaning": "BUPERS"
  },
  {
    "term": "CAMP H. M. SMITH, HI",
    "meaning": "CamSmh"
  },
  {
    "term": "CAMP J. H. PENDLETON, OCEANSIDE, CA",
    "meaning": "CamPen"
  },
  {
    "term": "CAMP LEJEUNE, NC",
    "meaning": "CamLej"
  },
  {
    "term": "CAMP S. D. BUTLER",
    "meaning": "CamBut"
  },
  {
    "term": "CARBAGAIR",
    "meaning": "While traveling via air outside the United States (XX) pounds baggage to accompany is authorized, an additional (number of pounds indicated) baggage is authorized as air cargo for shipment under the same class of priority."
  },
  {
    "term": "CARBASO",
    "meaning": "Carry out unexecuted portion basic orders."
  },
  {
    "term": "CC",
    "meaning": "Cost Code."
  },
  {
    "term": "CENTRAL INTELLIGENCE AGENCY",
    "meaning": "CIA"
  },
  {
    "term": "CHAIRMAN, JOINT CHIEFS OF STAFF",
    "meaning": "CJCS"
  },
  {
    "term": "CHIEF OF NAVAL AIR TRAINING",
    "meaning": "CNATRA"
  },
  {
    "term": "CHIEF OF NAVAL OPERATIONS",
    "meaning": "CNO"
  },
  {
    "term": "CHIEF OF STAFF, UNITED STATES AIR FORCE",
    "meaning": "CSAF"
  },
  {
    "term": "CHIEF OF STAFF, UNITED STATES ARMY",
    "meaning": "CSA"
  },
  {
    "term": "CIC",
    "meaning": "Customer Identification Code."
  },
  {
    "term": "CIPAP",
    "meaning": "Authority is granted to make such changes in above itinerary and to proceed to such additional places as may be necessary for accomplishment of this mission."
  },
  {
    "term": "CIVIL AFFAIRS GROUP",
    "meaning": "CAG"
  },
  {
    "term": "COMBAT SERVICE SUPPORT DETACHMENT",
    "meaning": "CSSDET"
  },
  {
    "term": "COMBAT SERVICE SUPPORT ELEMENT",
    "meaning": "CSSE"
  },
  {
    "term": "COMMAND AND STAFF COLLEGE",
    "meaning": "C&SC"
  },
  {
    "term": "COMMANDER IN CHIEF, FORCES COMMAND",
    "meaning": "CINCFOR"
  },
  {
    "term": "COMMANDER IN CHIEF, MILITARY AIRLIFT COMMAND",
    "meaning": "CINCMAC"
  },
  {
    "term": "COMMANDER IN CHIEF, STRATEGIC AIR COMMAND",
    "meaning": "CINCSAC"
  },
  {
    "term": "COMMANDER IN CHIEF, U.S. ATLANTIC COMMAND",
    "meaning": "USCINCLANT"
  },
  {
    "term": "COMMANDER IN CHIEF, U.S. CENTRAL COMMAND",
    "meaning": "USCINCCENT"
  },
  {
    "term": "COMMANDER IN CHIEF, U.S. PACIFIC COMMAND",
    "meaning": "USCINCPAC"
  },
  {
    "term": "COMMANDER IN CHIEF, U.S. SOUTHERN COMMAND",
    "meaning": "USCINCSO"
  },
  {
    "term": "COMMANDER IN CHIEF, U.S. SPACE COMMAND",
    "meaning": "USCINCSPACE"
  },
  {
    "term": "COMMANDER IN CHIEF, U.S. SPECIAL OPERATIONS COMMAND",
    "meaning": "USCINCSOC"
  },
  {
    "term": "COMMANDER IN CHIEF, U.S. TRANSPORTATION COMMAND",
    "meaning": "USCINCTRANS"
  },
  {
    "term": "COMMANDER, AMPHIBIOUS TASK FORCE",
    "meaning": "CATF"
  },
  {
    "term": "COMMANDER, LANDING FORCE",
    "meaning": "CLF"
  },
  {
    "term": "COMMANDER, MARINE CORPS AIR BASE",
    "meaning": "COMCAB"
  },
  {
    "term": "COMMANDER, MARINE CORPS AIR BASE, EASTERN AREA",
    "meaning": "COMCABEAST"
  },
  {
    "term": "COMMANDER, MARINE CORPS AIR BASE, WESTERN AREA",
    "meaning": "COMCABWEST"
  },
  {
    "term": "COMMANDER, MARINE CORPS BASES, PACIFIC",
    "meaning": "COMDRMARCORBASEPAC"
  },
  {
    "term": "COMMANDER, MARINE CORPS FORCES, ATLANTIC",
    "meaning": "COMDRMARFORLANT"
  },
  {
    "term": "COMMANDER, MARINE CORPS FORCES, EUROPE",
    "meaning": "COMDRMARFOREUR"
  },
  {
    "term": "COMMANDER, MARINE CORPS FORCES, PACIFIC",
    "meaning": "COMDRMARFORPAC"
  },
  {
    "term": "COMMANDER, MARINE CORPS SCHOOLS",
    "meaning": "COMDR, MCSCOLS"
  },
  {
    "term": "COMMANDER, MARINE CORPS SYSTEMS COMMAND",
    "meaning": "COMDRMARCORSYSCOM"
  },
  {
    "term": "COMPANY",
    "meaning": "Co"
  },
  {
    "term": "COMPDUINS",
    "meaning": "Upon completion of duty under instruction."
  },
  {
    "term": "COMPRET",
    "meaning": "Upon completion thereof return to duty station and resume regular duties."
  },
  {
    "term": "COMPTEM",
    "meaning": "Upon completion of temporary duty."
  },
  {
    "term": "COMPTEMINS",
    "meaning": "Upon completion of temporary duty under instruction."
  },
  {
    "term": "COMPTROLLER OF THE NAVY",
    "meaning": "NAVCOMPT"
  },
  {
    "term": "COMPUTER SCIENCE SCHOOL",
    "meaning": "CSScol"
  },
  {
    "term": "COT",
    "meaning": "Consecutive overseas tour."
  },
  {
    "term": "COUNTERINTELLIGENCE TEAM",
    "meaning": "CIT"
  },
  {
    "term": "DATA PROCESSING INSTALLATION",
    "meaning": "DPI"
  },
  {
    "term": "DATEDSG",
    "meaning": "On such date as the commanding general, commanding officer or other competent authority may designate."
  },
  {
    "term": "DAUS",
    "meaning": "Date arrived United States."
  },
  {
    "term": "DAUSDNR",
    "meaning": "Date arrived United States, dependents not restricted."
  },
  {
    "term": "DEFENSE COMMUNICATIONS",
    "meaning": "DCA"
  },
  {
    "term": "DEFENSE FINANCE AND ACCOUNTING SERVICE",
    "meaning": "DFAS"
  },
  {
    "term": "DEFENSE FINANCE AND ACCOUNTING SERVICE-KANSAS CITY CENTER",
    "meaning": "DFAS-KCC"
  },
  {
    "term": "DEFENSE INFORMATION SYSTEMS AGENCY",
    "meaning": "DISA"
  },
  {
    "term": "DEFENSE INTELLIGENCE AGENCY",
    "meaning": "DIA"
  },
  {
    "term": "DEFENSE LANGUAGE INSTITUTE",
    "meaning": "DLI"
  },
  {
    "term": "DEFENSE LOGISTICS AGENCY",
    "meaning": "DLA"
  },
  {
    "term": "DEFENSE MANPOWER DATA CENTER",
    "meaning": "DMDC"
  },
  {
    "term": "DEFENSE MAPPING AGENCY",
    "meaning": "DMA"
  },
  {
    "term": "DEFENSE MAPPING SCHOOL",
    "meaning": "DMSCOL"
  },
  {
    "term": "DEFENSE NUCLEAR AGENCY",
    "meaning": "DNA"
  },
  {
    "term": "DELREP",
    "meaning": "Authorized to delay (no. of days indicated), provided no excess leave involved, in reporting in compliance with these orders. Such delay to count as leave. Keep old and new duty stations advised of leave address."
  },
  {
    "term": "DELREPANY",
    "meaning": "Authorized to delay (no. of days indicated), provided no excess leave involved, and all of which may be taken prior to or after reporting to temporary duty station(s); such delay to count as leave. No additional cost to the Government involved. Keep old and new duty station advised to leave address."
  },
  {
    "term": "DELREPARUS",
    "meaning": "Authorized to delay (no. of days indicated or until date indicated) in returning to the duty station, such delay to count as leave, provided no excess leave involved and at no additional cost to the Government. Keep duty station advised to leave address."
  },
  {
    "term": "DELURN",
    "meaning": "Authorized to delay (no. of days indicated or until date indicated) in returning to the duty station, such delay to count as leave, provided no excess leave involved and at no additional cost to the Government. Keep duty station advised of leave address."
  },
  {
    "term": "DEPARTMENT OF COMMERCE",
    "meaning": "DoC"
  },
  {
    "term": "DEPARTMENT OF DEFENSE",
    "meaning": "DoD"
  },
  {
    "term": "DEPARTMENT OF HEALTH AND HUMAN SERVICES",
    "meaning": "DHHS"
  },
  {
    "term": "DEPARTMENT OF THE NAVY",
    "meaning": "DON"
  },
  {
    "term": "DEPARTMENT OF TRANSPORTATION",
    "meaning": "DoT"
  },
  {
    "term": "DEPARTMENT OF VETERAN AFFAIRS",
    "meaning": "DVA"
  },
  {
    "term": "DETACHMENT",
    "meaning": "Det"
  },
  {
    "term": "DIFDEN",
    "meaning": "Duty in a flying status, flight activity denied."
  },
  {
    "term": "DIFOP",
    "meaning": "Duty in a flying status involving operational flights."
  },
  {
    "term": "DIFOPINS",
    "meaning": "Duty under instruction in a flying status involving operational or training flights."
  },
  {
    "term": "DIFOPSODA",
    "meaning": "Duty in a flying status involving operational or training flights within the (command or activity) as may be designated."
  },
  {
    "term": "DIFOPTECH",
    "meaning": "Duty as a technical observer in a flying status involving operational or training flights."
  },
  {
    "term": "DIFOT",
    "meaning": "Duty in a flying status involving operational or training flights. *(May be used followed by \"crew\" or \"noncrew\" to be translated \"as crewmember\" or \"as noncrewmember\".)*"
  },
  {
    "term": "DIFPRO",
    "meaning": "Duty in a flying status involving proficiency flights."
  },
  {
    "term": "DIRECTORATE FOR INFORMATION AND RESOURCE MANAGEMENT",
    "meaning": "DIRM"
  },
  {
    "term": "DIRLAUTH",
    "meaning": "Direct liaison authorized."
  },
  {
    "term": "DISCIPLINARY BARRACKS",
    "meaning": "DisBks"
  },
  {
    "term": "DISTREAT",
    "meaning": "Upon being discharged from treatment."
  },
  {
    "term": "DIVISION",
    "meaning": "Div"
  },
  {
    "term": "DUINS",
    "meaning": "Duty Under Instruction."
  },
  {
    "term": "DUSODA",
    "meaning": "Duty within the (command or activity) as the (command or activity) may designate."
  },
  {
    "term": "DUSTA",
    "meaning": "Duty Station."
  },
  {
    "term": "ENGINEER SUPPORT BATTALION",
    "meaning": "ESB"
  },
  {
    "term": "EXACCT",
    "meaning": "Expenditure account."
  },
  {
    "term": "EXPEDITIONARY AIRFIELD",
    "meaning": "EAF"
  },
  {
    "term": "FAGAIRTRANS",
    "meaning": "(Via) first available Government air transportation."
  },
  {
    "term": "FAGSURTRANS",
    "meaning": "(Via) first available Government surface transportation."
  },
  {
    "term": "FAGTRANS",
    "meaning": "(Via) first available Government transportation."
  },
  {
    "term": "FAIRTRANS",
    "meaning": "(Via) first available air transportation."
  },
  {
    "term": "FAR EAST NETWORK",
    "meaning": "FEN"
  },
  {
    "term": "FATRANS",
    "meaning": "(Via) first available transportation."
  },
  {
    "term": "FEDERAL AVIATION ADMINISTRATION",
    "meaning": "FAA"
  },
  {
    "term": "FEDERAL BUREAU OF INVESTIGATION",
    "meaning": "FBI"
  },
  {
    "term": "FEDERAL BUREAU OF PRISONS",
    "meaning": "FBOP"
  },
  {
    "term": "FEDERAL EMERGENCY MANAGEMENT AGENCY",
    "meaning": "FEMA"
  },
  {
    "term": "FIELD ARTILLERY SCHOOL",
    "meaning": "FAS"
  },
  {
    "term": "FIELD MEDICAL SERVICE SCHOOL",
    "meaning": "FMSS"
  },
  {
    "term": "FIELD MUSIC SCHOOL",
    "meaning": "FMS"
  },
  {
    "term": "FIELD SUPPLY AND MAINTENANCE ANALYSIS OFFICE",
    "meaning": "FSMAO"
  },
  {
    "term": "FIRE TEAM",
    "meaning": "ftm"
  },
  {
    "term": "FIXED-WING SUPPORT SQUADRON",
    "meaning": "FWSS"
  },
  {
    "term": "FLEET ANTITERRORISM SECURITY TEAM",
    "meaning": "FAST"
  },
  {
    "term": "FLEET HOMETOWN NEWS CENTER",
    "meaning": "FHTNC"
  },
  {
    "term": "FLEET MARINE CORPS RESERVE",
    "meaning": "FMCR"
  },
  {
    "term": "FLEET MARINE FORCE",
    "meaning": "FMF"
  },
  {
    "term": "FLEET MARINE FORCE ATLANTIC",
    "meaning": "FMFLANT"
  },
  {
    "term": "FLEET MARINE FORCE EUROPE",
    "meaning": "FMFEUR"
  },
  {
    "term": "FLEET MARINE FORCE PACIFIC",
    "meaning": "FMFPAC"
  },
  {
    "term": "FLEET READINESS SQUADRON",
    "meaning": "FRS"
  },
  {
    "term": "FORCE AUTOMATED SERVICE CENTER",
    "meaning": "FASC"
  },
  {
    "term": "FORCE SERVICE SUPPORT GROUP",
    "meaning": "FSSG"
  },
  {
    "term": "FORWARD ANTIAIR DEFENSE",
    "meaning": "FAAD"
  },
  {
    "term": "FURNARSSN",
    "meaning": "Furnish full names, rates, and social security numbers of Marines transferred per this directive."
  },
  {
    "term": "FURNDISBOFF",
    "meaning": "Furnish the disbursing officer carrying your pay accounts a copy of these orders bearing all endorsements."
  },
  {
    "term": "FYI",
    "meaning": "For your information."
  },
  {
    "term": "GENERAL ACCOUNTING OFFICE",
    "meaning": "GAO"
  },
  {
    "term": "GOVAIR",
    "meaning": "Including Government air. *(Phrase equivalent usually used in combination.)*"
  },
  {
    "term": "GOVAIRDIR",
    "meaning": "Travel via Government aircraft is directed (between points specified) where necessary to expedite completion of this duty. Class priority is certified."
  },
  {
    "term": "GOVAIRDIROUT",
    "meaning": "Travel via Government aircraft is directed Outside the U.S. Class priority is certified."
  },
  {
    "term": "GOVAIRDIRVAIL",
    "meaning": "Travel via Government aircraft is directed (between points specified) where available. Class priority is certified."
  },
  {
    "term": "GOVAIRSUR",
    "meaning": "Travel via Government air and/or surface is authorized."
  },
  {
    "term": "GOVAIRSURDIR",
    "meaning": "Travel via Government air and/or surface vessel is directed."
  },
  {
    "term": "GOVAIRSURDIRVAIL",
    "meaning": "Travel via Government air and/or surface vessel is directed (between points specified) where available. Class priority is certified."
  },
  {
    "term": "GOVMERAIRDIR",
    "meaning": "In performing this travel Government air and/or Government procured commercial air is directed."
  },
  {
    "term": "GROUP",
    "meaning": "Gru"
  },
  {
    "term": "HEADQUARTERS AND HEADQUARTERS SQUADRON",
    "meaning": "HQHQRON"
  },
  {
    "term": "HEADQUARTERS AND SERVICE",
    "meaning": "HQSVC"
  },
  {
    "term": "HEADQUARTERS MARINE CORPS",
    "meaning": "HQMC"
  },
  {
    "term": "ICW",
    "meaning": "Insure compliance with."
  },
  {
    "term": "IMMUNQUIRED",
    "meaning": "Immediately upon receipt of these orders obtain immunization required for areas to be visited. Procure properly completed NavMed 585 (U.S. Navy Immunization Record)."
  },
  {
    "term": "INSPECTOR-INSTRUCTOR STAFF",
    "meaning": "I-ISTF"
  },
  {
    "term": "INTERROGATOR-TRANSLATOR TEAM",
    "meaning": "ITT"
  },
  {
    "term": "INTERROGATOR-TRANSLATOR UNIT",
    "meaning": "ITU"
  },
  {
    "term": "IPCOT",
    "meaning": "In-place Consecutive overseas tour."
  },
  {
    "term": "IRA",
    "meaning": "Intermediate reporting activity."
  },
  {
    "term": "IRT",
    "meaning": "In reference to; In response to."
  },
  {
    "term": "JOINT CHIEFS OF STAFF",
    "meaning": "JCS"
  },
  {
    "term": "JOINT DEPLOYMENT AGENCY",
    "meaning": "JDA"
  },
  {
    "term": "JOINT DOCTRINE CENTER",
    "meaning": "JDC"
  },
  {
    "term": "JOINT ELECTRONIC WARFARE CENTER",
    "meaning": "JEWC"
  },
  {
    "term": "JOINT PUBLIC AFFAIRS OFFICE",
    "meaning": "JPAO"
  },
  {
    "term": "JOINT STRATEGIC TARGET PLANNING STAFF",
    "meaning": "JSTPS"
  },
  {
    "term": "JOINT TASK FORCE",
    "meaning": "JTF"
  },
  {
    "term": "JOINT U.S. MILITARY ASSISTANCE GROUP",
    "meaning": "JUSMAG"
  },
  {
    "term": "JOINT WARFARE SYSTEM",
    "meaning": "JWC"
  },
  {
    "term": "LANDING FORCE TRAINING COMMAND",
    "meaning": "LFTC"
  },
  {
    "term": "LANDING SUPPORT BATTALION",
    "meaning": "LSB"
  },
  {
    "term": "LCPCSO",
    "meaning": "Low cost permanent change of station orders."
  },
  {
    "term": "LIGHT ANTIAIRCRAFT MISSILE",
    "meaning": "LAAM"
  },
  {
    "term": "LIGHT ARMORED INFANTRY",
    "meaning": "LAI"
  },
  {
    "term": "LOW ALTITUDE AIR DEFENSE",
    "meaning": "LAAD"
  },
  {
    "term": "MANPOWER INFORMATION SYSTEMS SUPPORT ACTIVITY",
    "meaning": "MISSA"
  },
  {
    "term": "MANPOWER INFORMATION SYSTEMS SUPPORT OFFICE",
    "meaning": "MISSO"
  },
  {
    "term": "MARADMIN",
    "meaning": "Marine Administrative Message."
  },
  {
    "term": "MARINE AERIAL TRANSPORT/REFUELER SQUADRON",
    "meaning": "VMGR"
  },
  {
    "term": "MARINE AIR CONTROL GROUP",
    "meaning": "MACG"
  },
  {
    "term": "MARINE AIR CONTROL SQUADRON",
    "meaning": "MACS"
  },
  {
    "term": "MARINE AIR FORCES",
    "meaning": "MARAIRFOR"
  },
  {
    "term": "MARINE AIR SUPPORT SQUADRON",
    "meaning": "MASS"
  },
  {
    "term": "MARINE AIR TRAFFIC CONTROL SQUADRON",
    "meaning": "MATCS"
  },
  {
    "term": "MARINE AIR TRAFFIC CONTROL UNIT",
    "meaning": "MATCU"
  },
  {
    "term": "MARINE AIR-GROUND TASK FORCE",
    "meaning": "MAGTF"
  },
  {
    "term": "MARINE AIR-GROUND TASK FORCE WARFIGHTING CENTER",
    "meaning": "MAGTFWFC"
  },
  {
    "term": "MARINE AIR-GROUND TRAINING AND EDUCATION CENTER",
    "meaning": "MAGTEC"
  },
  {
    "term": "MARINE AIRCRAFT GROUP",
    "meaning": "MAG"
  },
  {
    "term": "MARINE AIRCRAFT WING",
    "meaning": "MAW"
  },
  {
    "term": "MARINE ALL WEATHER ATTACK SQUADRON",
    "meaning": "VMA(AW)"
  },
  {
    "term": "MARINE ALL WEATHER FIGHTER TRAINING SQUADRON",
    "meaning": "VMFAT"
  },
  {
    "term": "MARINE ATTACK SQUADRON",
    "meaning": "VMA"
  },
  {
    "term": "MARINE ATTACK TRAINING SQUADRON",
    "meaning": "VMAT"
  },
  {
    "term": "MARINE AVIATION DETACHMENT",
    "meaning": "MAD"
  },
  {
    "term": "MARINE AVIATION LOGISTICS SQUADRON",
    "meaning": "MALS"
  },
  {
    "term": "MARINE AVIATION TRAINING SUPPORT GROUP",
    "meaning": "MATSG"
  },
  {
    "term": "MARINE AVIATION WEAPONS AND TACTICS SQUADRON",
    "meaning": "MAWTS"
  },
  {
    "term": "MARINE BARRACKS",
    "meaning": "MARBKS"
  },
  {
    "term": "MARINE COMBAT CREW READINESS TRAINING GROUP",
    "meaning": "MCCRTG"
  },
  {
    "term": "MARINE CORPS ABSENTEE COLLECTION UNIT",
    "meaning": "MCACU"
  },
  {
    "term": "MARINE CORPS ADMINISTRATIVE ANALYSIS TEAM",
    "meaning": "MCAAT"
  },
  {
    "term": "MARINE CORPS ADMINISTRATIVE ANALYSIS TEAM, EAST COAST",
    "meaning": "MCAAT-EAST"
  },
  {
    "term": "MARINE CORPS ADMINISTRATIVE ANALYSIS TEAM, WEST COAST",
    "meaning": "MCAAT-WEST"
  },
  {
    "term": "MARINE CORPS ADMINISTRATIVE DETACHMENT",
    "meaning": "MCAD"
  },
  {
    "term": "MARINE CORPS AIR BASE -S",
    "meaning": "MCAB"
  },
  {
    "term": "MARINE CORPS AIR FACILITY",
    "meaning": "MCAF"
  },
  {
    "term": "MARINE CORPS AIR STATION",
    "meaning": "MCAS"
  },
  {
    "term": "MARINE CORPS AIR-GROUND COMBAT CENTER",
    "meaning": "MCAGCC"
  },
  {
    "term": "MARINE CORPS ARTILLERY DETACHMENT",
    "meaning": "MCARTYDet"
  },
  {
    "term": "MARINE CORPS AUTOMATED SERVICES CENTER",
    "meaning": "MCASC"
  },
  {
    "term": "MARINE CORPS AUXILIARY AIR FACILITY",
    "meaning": "MCAAF"
  },
  {
    "term": "MARINE CORPS AUXILIARY AIR STATION",
    "meaning": "MCAAS"
  },
  {
    "term": "MARINE CORPS AUXILIARY LANDING FIELD",
    "meaning": "MCALF"
  },
  {
    "term": "MARINE CORPS BASE",
    "meaning": "MCB"
  },
  {
    "term": "MARINE CORPS COMBAT DEVELOPMENT COMMAND",
    "meaning": "MCCDC"
  },
  {
    "term": "MARINE CORPS COMMAND CENTER",
    "meaning": "MCCC"
  },
  {
    "term": "MARINE CORPS DETACHMENT",
    "meaning": "MCDet"
  },
  {
    "term": "MARINE CORPS DISTRICT",
    "meaning": "MCD"
  },
  {
    "term": "MARINE CORPS INSTITUTE",
    "meaning": "MCI"
  },
  {
    "term": "MARINE CORPS LOGISTICS BASE",
    "meaning": "MCLB"
  },
  {
    "term": "MARINE CORPS LOGISTICS BASES",
    "meaning": "MCLBASES"
  },
  {
    "term": "MARINE CORPS MOUNTAIN WARFARE TRAINING CENTER",
    "meaning": "MCMWTC"
  },
  {
    "term": "MARINE CORPS RECRUIT DEPOT",
    "meaning": "MCRD"
  },
  {
    "term": "MARINE CORPS RECRUIT DEPOT/EASTERN RECRUITING REGION",
    "meaning": "MCRD/ERR"
  },
  {
    "term": "MARINE CORPS RECRUIT DEPOT/WESTERN RECRUITING REGION",
    "meaning": "MCRD/WRR"
  },
  {
    "term": "MARINE CORPS RECRUITING AND RECRUIT TRAINING COMMAND",
    "meaning": "MCR-RTC"
  },
  {
    "term": "MARINE CORPS RECRUITING STATION",
    "meaning": "USMC RS"
  },
  {
    "term": "MARINE CORPS RECRUITING SUBSTATION",
    "meaning": "USMC RSS"
  },
  {
    "term": "MARINE CORPS RESERVE",
    "meaning": "USMCR"
  },
  {
    "term": "MARINE CORPS RESERVE SUPPORT COMMAND",
    "meaning": "MCRSC"
  },
  {
    "term": "MARINE CORPS RESERVE TRAINING CENTER",
    "meaning": "MCRTC"
  },
  {
    "term": "MARINE CORPS SCHOOLS",
    "meaning": "MARSCHOOL"
  },
  {
    "term": "MARINE CORPS SECURITY FORCE -S",
    "meaning": "MCSF"
  },
  {
    "term": "MARINE CORPS SERVICE SUPPORT SCHOOLS",
    "meaning": "MCSSS"
  },
  {
    "term": "MARINE CORPS SUPPORT ACTIVITY",
    "meaning": "MCSA"
  },
  {
    "term": "MARINE CORPS SYSTEMS COMMAND",
    "meaning": "MARCORSYSCOM"
  },
  {
    "term": "MARINE CORPS TACTICAL SYSTEM SUPPORT ACTIVITY",
    "meaning": "MCTSSA"
  },
  {
    "term": "MARINE CORPS UNIVERSITY",
    "meaning": "MCU"
  },
  {
    "term": "MARINE DETACHMENT",
    "meaning": "MARDET"
  },
  {
    "term": "MARINE DIVISION",
    "meaning": "MarDiv"
  },
  {
    "term": "MARINE ELECTRONIC WARFARE SQUADRON",
    "meaning": "VMAQ"
  },
  {
    "term": "MARINE EXPEDITIONARY BRIGADE",
    "meaning": "MEB"
  },
  {
    "term": "MARINE EXPEDITIONARY CORPS",
    "meaning": "MEC"
  },
  {
    "term": "MARINE EXPEDITIONARY FORCE",
    "meaning": "MEF"
  },
  {
    "term": "MARINE EXPEDITIONARY UNIT",
    "meaning": "MEU"
  },
  {
    "term": "MARINE EXPEDITIONARY UNIT (SPECIAL OPERATIONS CAPABLE)",
    "meaning": "MEU(SOC)"
  },
  {
    "term": "MARINE EXPEDITIONARY UNIT SERVICE SUPPORT GROUP",
    "meaning": "MEUSSG"
  },
  {
    "term": "MARINE FIGHTER ATTACK SQUADRON",
    "meaning": "VMFA"
  },
  {
    "term": "MARINE FIGHTER TRAINING SQUADRON",
    "meaning": "VMFT"
  },
  {
    "term": "MARINE FORCE RESERVE",
    "meaning": "MARFORRES"
  },
  {
    "term": "MARINE FORCES, ATLANTIC",
    "meaning": "MARFORLANT"
  },
  {
    "term": "MARINE FORCES, PACIFIC",
    "meaning": "MARFORPAC"
  },
  {
    "term": "MARINE GROUND FORCES",
    "meaning": "MARGNDFOR"
  },
  {
    "term": "MARINE HEADQUARTERS AND MAINTENANCE SQUADRON",
    "meaning": "H&MS"
  },
  {
    "term": "MARINE HEAVY HELICOPTER SQUADRON",
    "meaning": "HMH"
  },
  {
    "term": "MARINE LIGHT ATTACK HELICOPTER SQUADRON",
    "meaning": "HMLA"
  },
  {
    "term": "MARINE LIGHT HELICOPTER SQUADRON",
    "meaning": "HML"
  },
  {
    "term": "MARINE MEDIUM HELICOPTER SQUADRON",
    "meaning": "HMM"
  },
  {
    "term": "MARINE OBSERVATION SQUADRON",
    "meaning": "VMO"
  },
  {
    "term": "MARINE OFFICER INSTRUCTOR",
    "meaning": "MOI"
  },
  {
    "term": "MARINE PHOTOGRAPHIC RECONNAISSANCE SQUADRON",
    "meaning": "VMFP"
  },
  {
    "term": "MARINE SECURITY GUARD BATTALION",
    "meaning": "MSGBn"
  },
  {
    "term": "MARINE SUPPORT BATTALION",
    "meaning": "MARSPTBn"
  },
  {
    "term": "MARINE WING COMMUNICATIONS SQUADRON",
    "meaning": "MWCS"
  },
  {
    "term": "MARINE WING HEADQUARTERS SQUADRON",
    "meaning": "MWHS"
  },
  {
    "term": "MARINE WING SUPPORT GROUP",
    "meaning": "MWSG"
  },
  {
    "term": "MARINE WING SUPPORT SQUADRON",
    "meaning": "MWSS"
  },
  {
    "term": "MARINE WING WEAPONS UNIT",
    "meaning": "MWWU"
  },
  {
    "term": "MARINES (WHEN REFERRING TO REGIMENTAL ORGANIZATIONS)",
    "meaning": "Mar"
  },
  {
    "term": "MARITIME PREPOSITIONING FORCE",
    "meaning": "MPF"
  },
  {
    "term": "MERAIR",
    "meaning": "Commercial air."
  },
  {
    "term": "MILITARY AIRLIFT COMMAND",
    "meaning": "MAC"
  },
  {
    "term": "MILITARY ASSISTANCE ADVISORY GROUP",
    "meaning": "MAAG"
  },
  {
    "term": "MILITARY ENTRANCE PROCESSING COMMAND",
    "meaning": "MEPCOM"
  },
  {
    "term": "MILITARY ENTRANCE PROCESSING STATION",
    "meaning": "MEPS"
  },
  {
    "term": "MILITARY SEALIFT COMMAND",
    "meaning": "MSC"
  },
  {
    "term": "MILITARY TRAFFIC MANAGEMENT COMMAND",
    "meaning": "MTMC"
  },
  {
    "term": "MITRE",
    "meaning": "Authorized to omit or revisit any of the mentioned places as deemed necessary."
  },
  {
    "term": "MITREVAR",
    "meaning": "Authorized to omit or revisit any of the mentioned places and to vary the itinerary as deemed necessary."
  },
  {
    "term": "MITVAR",
    "meaning": "Authorized to omit any of the mentioned places and to vary the itinerary as may be deemed necessary."
  },
  {
    "term": "MOBILE COMBAT SERVICE SUPPORT DETACHMENT",
    "meaning": "MCSSD"
  },
  {
    "term": "MOBILE TRAINING TEAM",
    "meaning": "MTT"
  },
  {
    "term": "MOBILIZATION TRAINING UNIT",
    "meaning": "MTU"
  },
  {
    "term": "MORALE, WELFARE AND RECREATION",
    "meaning": "MWR"
  },
  {
    "term": "MORALE, WELFARE AND RECREATION SUPPORT ACTIVITY",
    "meaning": "MWRSPTACT"
  },
  {
    "term": "MPMC",
    "meaning": "Military Personnel, Marine Corps."
  },
  {
    "term": "NATIONAL AERONAUTICS AND SPACE ADMINISTRATION",
    "meaning": "NASA"
  },
  {
    "term": "NATIONAL DEFENSE UNIVERSITY",
    "meaning": "NDU"
  },
  {
    "term": "NATIONAL MILITARY COMMAND CENTER",
    "meaning": "NMCC"
  },
  {
    "term": "NATIONAL OCEANIC AND ATMOSPHERIC ADMINISTRATION",
    "meaning": "NOAA"
  },
  {
    "term": "NATIONAL SECURITY AGENCY",
    "meaning": "NSA"
  },
  {
    "term": "NATIONAL WAR COLLEGE",
    "meaning": "NWC"
  },
  {
    "term": "NATO DEFENSE COLLEGE",
    "meaning": "NADEFCOL"
  },
  {
    "term": "NAVAL ACADEMY PREPARATORY SCHOOL",
    "meaning": "NAPS"
  },
  {
    "term": "NAVAL AIR FACILITY- NAVAL AIRCRAFT FACTORY",
    "meaning": "NAF"
  },
  {
    "term": "NAVAL AIR MISSILE TEST CENTER",
    "meaning": "NAMTC"
  },
  {
    "term": "NAVAL AIR RESERVE TRAINING UNIT",
    "meaning": "NARTU"
  },
  {
    "term": "NAVAL AIR REWORK FACILITY",
    "meaning": "NARF"
  },
  {
    "term": "NAVAL AIR STATION",
    "meaning": "NAS"
  },
  {
    "term": "NAVAL AIR SYSTEMS COMMAND",
    "meaning": "NAVAIRSYSCOM"
  },
  {
    "term": "NAVAL AIR TECHNICAL TRAINING CENTER",
    "meaning": "NATTC"
  },
  {
    "term": "NAVAL AIR TRAINING BASE",
    "meaning": "NATB"
  },
  {
    "term": "NAVAL AMMUNITION DEPOT",
    "meaning": "NAD"
  },
  {
    "term": "NAVAL AMPHIBIOUS BASE",
    "meaning": "NAB"
  },
  {
    "term": "NAVAL BASE",
    "meaning": "NB"
  },
  {
    "term": "NAVAL COMMUNICATIONS STATION",
    "meaning": "NAVCOMSTA"
  },
  {
    "term": "NAVAL CONSTRUCTION BATTALION",
    "meaning": "NCB"
  },
  {
    "term": "NAVAL CRIMINAL INVESTIGATIVE SERVICE",
    "meaning": "NCIS"
  },
  {
    "term": "NAVAL DISTRICT",
    "meaning": "NavDist"
  },
  {
    "term": "NAVAL FACILITY",
    "meaning": "NAVFAC"
  },
  {
    "term": "NAVAL FORCE -S",
    "meaning": "NAVFOR"
  },
  {
    "term": "NAVAL HOSPITAL",
    "meaning": "USNH"
  },
  {
    "term": "NAVAL MEDICAL COMMAND",
    "meaning": "NAVMEDCOM"
  },
  {
    "term": "NAVAL MILITARY PERSONNEL COMMAND",
    "meaning": "NMPC"
  },
  {
    "term": "NAVAL POST GRADUATE SCHOOL",
    "meaning": "NPS"
  },
  {
    "term": "NAVAL RESERVE OFFICERS TRAINING CORPS",
    "meaning": "NROTC"
  },
  {
    "term": "NAVAL SHIPYARD",
    "meaning": "NAVSHIPYD"
  },
  {
    "term": "NAVAL STATION",
    "meaning": "NAVSTA"
  },
  {
    "term": "NAVAL SUPPLY DEPOT",
    "meaning": "NSD"
  },
  {
    "term": "NAVAL TRAINING CENTER",
    "meaning": "NTC"
  },
  {
    "term": "NAVAL WEAPONS STATION",
    "meaning": "NWPNSTA"
  },
  {
    "term": "NAVY ADVISORY GROUP",
    "meaning": "NAG"
  },
  {
    "term": "NAVY AND MARINE CORPS APPELLATE LEAVE ACTIVITY",
    "meaning": "NAMALA"
  },
  {
    "term": "NAVY AND MARINE CORPS RESERVE TRAINING CENTER",
    "meaning": "N&MCRTC"
  },
  {
    "term": "NONCOMMISSIONED OFFICER SCHOOL",
    "meaning": "NCOScol"
  },
  {
    "term": "NOPROCAN",
    "meaning": "If not already proceeded, orders (identified by date-time-group which follows are canceled."
  },
  {
    "term": "NORTH AMERICAN AEROSPACE DEFENSE COMMAND",
    "meaning": "NORAD"
  },
  {
    "term": "NORTH ATLANTIC TREATY ORGANIZATION",
    "meaning": "NATO"
  },
  {
    "term": "NUCLEAR ORDNANCE PLATOON",
    "meaning": "NOP"
  },
  {
    "term": "OC",
    "meaning": "Object class."
  },
  {
    "term": "OCD",
    "meaning": "Overseas control date."
  },
  {
    "term": "OCONUS",
    "meaning": "Outside 48 contiguous states and District of Columbia."
  },
  {
    "term": "OFFICE OF LEGISLATIVE AFFAIRS",
    "meaning": "OLA"
  },
  {
    "term": "OFFICE OF NAVAL INTELLIGENCE",
    "meaning": "ONI"
  },
  {
    "term": "OFFICE OF THE CHIEF OF NAVAL OPERATIONS",
    "meaning": "OPNAV"
  },
  {
    "term": "OFFICE OF THE SECRETARY OF DEFENSE",
    "meaning": "OSD"
  },
  {
    "term": "OFFICER CANDIDATES SCHOOL",
    "meaning": "OCS"
  },
  {
    "term": "PDS",
    "meaning": "Permanent duty station."
  },
  {
    "term": "PERGRA",
    "meaning": "Permission granted."
  },
  {
    "term": "PERNOGRA",
    "meaning": "Permission not granted."
  },
  {
    "term": "PERSONNEL ADMINISTRATIVE SCHOOL",
    "meaning": "PAScol"
  },
  {
    "term": "PLATOON",
    "meaning": "plat"
  },
  {
    "term": "POV",
    "meaning": "Privately owned vehicle."
  },
  {
    "term": "PROIMREP",
    "meaning": "Proceed immediately to location of ship, commander or station designated and upon arrival report for duty or purpose indicated."
  },
  {
    "term": "PROREP",
    "meaning": "Proceed to (location of ship, commander, or station by group(s)) immediately following and upon arrival report for duty or purpose indicated)."
  },
  {
    "term": "PROTIMEARR",
    "meaning": "Proceed in time to arrive on (date indicated) to activity or station designated."
  },
  {
    "term": "PROTIMEREP",
    "meaning": "Proceed in time to report to activity or station designated not later than (hour and/or date indicted)."
  },
  {
    "term": "PROVMAIN",
    "meaning": "All other provisions of present orders to remain in effect."
  },
  {
    "term": "PROVOST MARSHALL OFFICE",
    "meaning": "PMO"
  },
  {
    "term": "PROWODELREP",
    "meaning": "Proceed without delay to location of ship, commander, designated and upon arrival report for duty or purpose indicated."
  },
  {
    "term": "PUBLIC HEALTH SERVICE",
    "meaning": "PHS"
  },
  {
    "term": "RADIO AND PANEL SECTION",
    "meaning": "R&PSec"
  },
  {
    "term": "RADIO INTELLIGENCE PLATOON",
    "meaning": "RadIP"
  },
  {
    "term": "RADIO RECONNAISSANCE PLATOON",
    "meaning": "RRP"
  },
  {
    "term": "RADIO RECONNAISSANCE TEAM",
    "meaning": "RRT"
  },
  {
    "term": "REGIMENT -AL",
    "meaning": "Regt"
  },
  {
    "term": "REGIMENTAL LANDING TEAM",
    "meaning": "RLT"
  },
  {
    "term": "RELACDU",
    "meaning": "Release from active duty."
  },
  {
    "term": "RELBY",
    "meaning": "When relieved by ."
  },
  {
    "term": "RESERVE AUGMENTATION UNIT",
    "meaning": "RAU"
  },
  {
    "term": "RESERVE SUPPORT UNIT",
    "meaning": "RSU"
  },
  {
    "term": "RFC",
    "meaning": "Relief for cause."
  },
  {
    "term": "RICCO",
    "meaning": "Reenlistment incentive considered complete."
  },
  {
    "term": "RNQ",
    "meaning": "Reason not qualified."
  },
  {
    "term": "ROCCO",
    "meaning": "Reenlistment option cycle complete."
  },
  {
    "term": "ROTARY WING SUPPORT SQUADRON",
    "meaning": "RWSS"
  },
  {
    "term": "SASSY MANAGEMENT UNIT",
    "meaning": "SMU"
  },
  {
    "term": "SCHOOL OF INFANTRY",
    "meaning": "SOI"
  },
  {
    "term": "SECNAVFIND",
    "meaning": "The Secretary of the Navy found on (date) that more than one permanent change of station was required by the exigencies of the service during the same fiscal year."
  },
  {
    "term": "SELECTED MARINE CORPS RESERVE",
    "meaning": "SMCR"
  },
  {
    "term": "SELECTED MARINE CORPS RESERVE, AVIATION",
    "meaning": "SMCR (A)"
  },
  {
    "term": "SELECTED MARINE CORPS RESERVE, GROUND",
    "meaning": "SMCR (G)"
  },
  {
    "term": "SFNP",
    "meaning": "Statement format not provided."
  },
  {
    "term": "SHORE FIRE CONTROL PARTY",
    "meaning": "SFCP"
  },
  {
    "term": "SHORE PARTY - SHORE PATROL",
    "meaning": "SP"
  },
  {
    "term": "SPECIAL PURPOSE MAGTF",
    "meaning": "SPF"
  },
  {
    "term": "SQUAD",
    "meaning": "sqd"
  },
  {
    "term": "SQUADRON",
    "meaning": "Sqdn"
  },
  {
    "term": "STAFF NONCOMMISSIONED OFFICER ACADEMY",
    "meaning": "SNCOA"
  },
  {
    "term": "STATION",
    "meaning": "Sta"
  },
  {
    "term": "STATION OPERATIONS AND MAINTENANCE SQUADRON",
    "meaning": "SOMS"
  },
  {
    "term": "STRATEGIC AIR COMMAND",
    "meaning": "SAC"
  },
  {
    "term": "SUBUNIT",
    "meaning": "SU"
  },
  {
    "term": "SUPREME ALLIED COMMANDER ATLANTIC",
    "meaning": "SACLant"
  },
  {
    "term": "SUPREME ALLIED COMMANDER EUROPE",
    "meaning": "SACEUR"
  },
  {
    "term": "SUPREME HEADQUARTERS ALLIED POWERS EUROPE",
    "meaning": "SHAPE"
  },
  {
    "term": "SURTRANS",
    "meaning": "(Via) first available Government transportation, not including air."
  },
  {
    "term": "SURVEILLANCE AND TARGET ACQUISITION",
    "meaning": "STA"
  },
  {
    "term": "SURVEILLANCE, RECONNAISSANCE, INTELLIGENCE",
    "meaning": "SRI"
  },
  {
    "term": "SURVEILLANCE, RECONNAISSANCE, INTELLIGENCE GROUP",
    "meaning": "SRIG"
  },
  {
    "term": "TARGET ACQUISITION BATTERY",
    "meaning": "TAB"
  },
  {
    "term": "TEMAC",
    "meaning": "Temporary active duty."
  },
  {
    "term": "TEMADDCON",
    "meaning": "Temporary additional duty in connection with."
  },
  {
    "term": "TEMADDINS",
    "meaning": "Temporary additional duty under instruction. (TAD at a formal school less than 20 weeks.)"
  },
  {
    "term": "TEMCCN",
    "meaning": "Temporary duty in connection with."
  },
  {
    "term": "TEMINS",
    "meaning": "Temporary duty under instruction. Temporary duty at a formal school en route to new PDS."
  },
  {
    "term": "THE BASIC SCHOOL",
    "meaning": "TBS"
  },
  {
    "term": "TOS",
    "meaning": "Time on Station."
  },
  {
    "term": "TRAFFIC MANAGEMENT OFFICE",
    "meaning": "TMO"
  },
  {
    "term": "TRAINING AND AUDIOVISUAL SUPPORT CENTER",
    "meaning": "TAVSC"
  },
  {
    "term": "TRAINING AND DOCTRINE COMMAND",
    "meaning": "TRADOC"
  },
  {
    "term": "TRAVCHAR",
    "meaning": "Cost of this travel is chargeable to appropriation or department designated following group(s) (Identifying numerals may be added.)"
  },
  {
    "term": "U.S. ARMY COMMAND AND GENERAL STAFF COLLEGE",
    "meaning": "USACGSC"
  },
  {
    "term": "U.S. COMMAND IN CHIEF, EUROPE",
    "meaning": "USCINCEUR"
  },
  {
    "term": "UNI",
    "meaning": "Unless otherwise indicated."
  },
  {
    "term": "UNITED SEAMAN'S SERVICE",
    "meaning": "USS"
  },
  {
    "term": "UNITED SERVICE ORGANIZATION",
    "meaning": "USO"
  },
  {
    "term": "UNITED STATES AIR FORCE",
    "meaning": "USAF"
  },
  {
    "term": "UNITED STATES AIR FORCE ACADEMY",
    "meaning": "USAFA"
  },
  {
    "term": "UNITED STATES ARMED FORCES INSTITUTE",
    "meaning": "USAFI"
  },
  {
    "term": "UNITED STATES ARMY",
    "meaning": "USA"
  },
  {
    "term": "UNITED STATES ARMY HOSPITAL",
    "meaning": "USAH"
  },
  {
    "term": "UNITED STATES CENTRAL COMMAND",
    "meaning": "USCENTCOM"
  },
  {
    "term": "UNITED STATES COAST GUARD",
    "meaning": "USCG"
  },
  {
    "term": "UNITED STATES COAST GUARD ACADEMY",
    "meaning": "USCGA"
  },
  {
    "term": "UNITED STATES FLEET ACTIVITIES",
    "meaning": "FltAct"
  },
  {
    "term": "UNITED STATES MARINE CORPS",
    "meaning": "USMC"
  },
  {
    "term": "UNITED STATES MARINE CORPS RESERVE",
    "meaning": "USMCR"
  },
  {
    "term": "UNITED STATES MILITARY ACADEMY",
    "meaning": "USMA"
  },
  {
    "term": "UNITED STATES NAVAL ACADEMY",
    "meaning": "USNA"
  },
  {
    "term": "UNITED STATES NAVAL ACTIVITIES",
    "meaning": "NavAct"
  },
  {
    "term": "UNITED STATES NAVAL ATTACHE",
    "meaning": "ALUSNA"
  },
  {
    "term": "UNITED STATES NAVAL TELETYPEWRITER EXCHANGE",
    "meaning": "NTX"
  },
  {
    "term": "UNITED STATES NAVY",
    "meaning": "USN"
  },
  {
    "term": "UNITED STATES NAVY RESERVE",
    "meaning": "USNR"
  },
  {
    "term": "UNITED STATES SPACE COMMAND",
    "meaning": "USSPACECOM"
  },
  {
    "term": "UNODIR",
    "meaning": "Unless otherwise directed."
  },
  {
    "term": "UNORDREVO",
    "meaning": "Unexecuted portion of orders (identified by reference number following) are revoked."
  },
  {
    "term": "WING",
    "meaning": "WING"
  }
];
