export interface Ssic {
  code: string;
  nomenclature: string;
}

export const SSICS: Ssic[] = [
  {"code": "8333", "nomenclature": "12 Inch/50 Caliber"},
  {"code": "8334", "nomenclature": "14 Inch/50 Caliber"},
  {"code": "8335", "nomenclature": "16 Inch/45 and 16 Inch/50 Caliber"},
  {"code": "8362", "nomenclature": "20mm"},
  {"code": "8031", "nomenclature": "20mm and 40mm Gun Ammunition"},
  {"code": "8032", "nomenclature": "3 Inch and 76mm Gun Ammunition"},
  {"code": "8310", "nomenclature": "3 Inch Guns"},
  {"code": "8311", "nomenclature": "3 Inch/50 Caliber"},
  {"code": "8312", "nomenclature": "3 Inch/70 Caliber"},
  {"code": "8361", "nomenclature": "30 Caliber and 50 Caliber"},
  {"code": "8363", "nomenclature": "40mm"},
  {"code": "8033", "nomenclature": "5 Inch and l27mm Gun Ammunition"},
  {"code": "8320", "nomenclature": "5 Inch Guns and Gun Mounts"},
  {"code": "8321", "nomenclature": "5 Inch/25 Caliber"},
  {"code": "8322", "nomenclature": "5 Inch/38 Caliber"},
  {"code": "8323", "nomenclature": "5 Inch/54 Caliber"},
  {"code": "8034", "nomenclature": "6 Inch and Larger Gun Ammunition"},
  {"code": "8330", "nomenclature": "6 Inch and Larger Guns and Gun Mounts"},
  {"code": "8331", "nomenclature": "6 Inch/ 47 Caliber"},
  {"code": "8313", "nomenclature": "76mm/62 Caliber"},
  {"code": "8332", "nomenclature": "8 Inch/55 Caliber"},
  {"code": "12630", "nomenclature": "Absence and Leave (Civilian Personnel)"},
  {"code": "1531", "nomenclature": "Academy, Naval Training"},
  {"code": "9071", "nomenclature": "Access"},
  {"code": "5102", "nomenclature": "Accident Investigation and Reporting"},
  {"code": "5101", "nomenclature": "Accident Prevention"},
  {"code": "7330", "nomenclature": "Accounting Reports and Returns"},
  {"code": "7562", "nomenclature": "Accounting Rulings, Precedents and Decisions"},
  {"code": "7410", "nomenclature": "Accounting, Civilian Labor"},
  {"code": "7420", "nomenclature": "Accounting, Civilian Payroll"},
  {"code": "7430", "nomenclature": "Accounting, Military Payroll"},
  {"code": "2283", "nomenclature": "Accounts and Inventory Control (COMSEC)"},
  {"code": "3891", "nomenclature": "Acoustic, Intelligence Production"},
  {"code": "3356", "nomenclature": "Acoustic Sensor Employment"},
  {"code": "3825", "nomenclature": "Acoustic, Intelligence Collection"},
  {"code": "3835", "nomenclature": "Acoustic, Intelligence Dissemination"},
  {"code": "3879", "nomenclature": "Acoustic, Intelligence Training"},
  {"code": "2324", "nomenclature": "ACP-117 Listings"},
  {"code": "8242", "nomenclature": "Acquisition and Tracking (Energy Weapons Control)"},
  {"code": "4210", "nomenclature": "Acquisition Assignments (Intra Navy)"},
  {"code": "4270", "nomenclature": "Acquisition Forms"},
  {"code": "4215", "nomenclature": "Acquisitions, Coordinated (within DoD)"},
  {"code": "4220", "nomenclature": "Acquisitions, Interdepartmental (Government)"},
  {"code": "12754", "nomenclature": "Actions, Suitability Disqualifications"},
  {"code": "1571", "nomenclature": "Active Duty for Training"},
  {"code": "9471", "nomenclature": "Active Electronic Countermeasures (ECM)"},
  {"code": "13443", "nomenclature": "Actuators (Hydraulic, Pneumatic and Lubrication Systems)"},
  {"code": "2340", "nomenclature": "Address Designators (General)"},
  {"code": "1110", "nomenclature": "Administration and Logistics (Recruiting)"},
  {"code": "5000", "nomenclature": "Administration and Management (General)"},
  {"code": "5291", "nomenclature": "Administration and Organization (Audiovisual)"},
  {"code": "5771", "nomenclature": "Administration and Policy (AFRTS)"},
  {"code": "3110", "nomenclature": "Administrative Assignment of Operating Forces of the Navy"},
  {"code": "2066", "nomenclature": "Administrative Telephone System"},
  {"code": "5221", "nomenclature": "Administrative Workload Management"},
  {"code": "5880", "nomenclature": "Admiralty (Law and Legal)"},
  {"code": "3205", "nomenclature": "ADP Support to Cryptologic Systems"},
  {"code": "4040", "nomenclature": "Advanced Base Program"},
  {"code": "3280", "nomenclature": "Advanced Cryptologic Systems Development (Cryptologic R&D)"},
  {"code": "2075", "nomenclature": "Advanced Research Projects Agency Network (ARPANET)"},
  {"code": "1430", "nomenclature": "Advancements in Rate or Rating"},
  {"code": "12752", "nomenclature": "Adverse Actions by Agencies"},
  {"code": "1140", "nomenclature": "Advertising (Recruiting)"},
  {"code": "4250", "nomenclature": "Advertising, Formal (Contracting)"},
  {"code": "7582", "nomenclature": "Advisory Accounting Reports"},
  {"code": "13485", "nomenclature": "Aerial Towing (Targets, Gliders)"},
  {"code": "3310", "nomenclature": "Aerial Warfare Procedures"},
  {"code": "13013", "nomenclature": "Aerodynamics and Hydrodynamics (Aircraft Characteristics)"},
  {"code": "13000", "nomenclature": "Aeronautical and Astronautical Material (General)"},
  {"code": "13600", "nomenclature": "Aeronautical Ground Support Equipment (General)"},
  {"code": "5080", "nomenclature": "Affairs, Civil, Military Government"},
  {"code": "12720", "nomenclature": "Affirmative Employment Program"},
  {"code": "5773", "nomenclature": "Afloat AFRT Operations"},
  {"code": "2700", "nomenclature": "Afloat Communications (General)"},
  {"code": "2790", "nomenclature": "Afloat Communications Support"},
  {"code": "2052", "nomenclature": "Afloat SATCOM Systems"},
  {"code": "10210", "nomenclature": "Agricultural Machinery"},
  {"code": "10200", "nomenclature": "Agricultural Machinery and Tools (General)"},
  {"code": "11015", "nomenclature": "Agriculture, Fish and Wildlife"},
  {"code": "1750", "nomenclature": "Aid, Dependents"},
  {"code": "1142", "nomenclature": "Aids (Recruit Advertising)"},
  {"code": "3531", "nomenclature": "Aids to Navigation (Training and Readiness)"},
  {"code": "2342", "nomenclature": "AIGs/CADs/General Messages"},
  {"code": "8515", "nomenclature": "Air and Surface Launched Torpedoes"},
  {"code": "3362", "nomenclature": "Air ASW (Warfare Procedures)"},
  {"code": "10220", "nomenclature": "Air Compressors and Pump"},
  {"code": "10230", "nomenclature": "Air Conditioning and Ventilating Equipment"},
  {"code": "9514", "nomenclature": "Air Conditioning System"},
  {"code": "3320", "nomenclature": "Air Defense (Warfare Procedures)"},
  {"code": "3872", "nomenclature": "Air (Intelligence Training)"},
  {"code": "9625", "nomenclature": "Air Ports, Fixed Port Lights and Windows"},
  {"code": "3103", "nomenclature": "Air Reserve Operations, Naval"},
  {"code": "9515", "nomenclature": "Air Revitalization Systems (Submarines)"},
  {"code": "3237", "nomenclature": "Air Systems (Cryptologic)"},
  {"code": "5452", "nomenclature": "Air Training Commands"},
  {"code": "4630", "nomenclature": "Air Transportation"},
  {"code": "3517", "nomenclature": "Air Warfare TAC D&E"},
  {"code": "9550", "nomenclature": "Air, Gas and Miscellaneous Fluid Systems"},
  {"code": "8516", "nomenclature": "Air, Surface and Underwater Launched Torpedoes"},
  {"code": "2531", "nomenclature": "Air/Ground Communications Systems (SI)"},
  {"code": "2254", "nomenclature": "Airborne Cryptographic Equipment"},
  {"code": "3236", "nomenclature": "Airborne Direct Support Operations"},
  {"code": "3316", "nomenclature": "Airborne Electronic Countermeasures"},
  {"code": "8380", "nomenclature": "Airborne Guns, Launchers and Racks"},
  {"code": "13484", "nomenclature": "Airborne Mine Countermeasures Systems"},
  {"code": "2045", "nomenclature": "Airborne National Command Post (ABNCP)"},
  {"code": "13220", "nomenclature": "Airborne Navigation, Automatic Flight Control, and Instrument Systems"},
  {"code": "13290", "nomenclature": "Airborne Radar"},
  {"code": "13240", "nomenclature": "Airborne Weapon (Fire Controls) Systems and Airborne Missile Guidance Systems (Gun Sights)"},
  {"code": "13100", "nomenclature": "Aircraft (General)"},
  {"code": "5756", "nomenclature": "Aircraft (Historical Matters)"},
  {"code": "13980", "nomenclature": "Aircraft Alarm and Signal Systems"},
  {"code": "13810", "nomenclature": "Aircraft Arresting, Barrier, and Barricade Recovery Equipment"},
  {"code": "13024", "nomenclature": "Aircraft Battle Damage Repair (ABDR)"},
  {"code": "13010", "nomenclature": "Aircraft Characteristics"},
  {"code": "13012", "nomenclature": "Aircraft Flying Qualities, Stability and Control"},
  {"code": "9588", "nomenclature": "Aircraft Handling, Servicing, and Storage"},
  {"code": "8551", "nomenclature": "Aircraft Laid Mines"},
  {"code": "9587", "nomenclature": "Aircraft Launch Support Systems"},
  {"code": "8512", "nomenclature": "Aircraft Launched Torpedoes"},
  {"code": "13020", "nomenclature": "Aircraft Maintenance"},
  {"code": "13650", "nomenclature": "Aircraft Maintenance Material Readiness List (AMMRL) Program"},
  {"code": "13054", "nomenclature": "Aircraft Modifications (Fleet Proposals)"},
  {"code": "13011", "nomenclature": "Aircraft Performance Characteristics"},
  {"code": "9586", "nomenclature": "Aircraft Recovery Support Systems"},
  {"code": "9780", "nomenclature": "Aircraft Related Weapons, Stowage, and Handling"},
  {"code": "13034", "nomenclature": "Aircraft Restrictions/Limitations"},
  {"code": "8042", "nomenclature": "Aircraft Rockets"},
  {"code": "13040", "nomenclature": "Aircraft Survivability/Vulnerability"},
  {"code": "13160", "nomenclature": "Aircraft Targets"},
  {"code": "13035", "nomenclature": "Aircraft/Stores Compatibility"},
  {"code": "13483", "nomenclature": "Airdropped Cargo Systems (Special Mission Systems)"},
  {"code": "13451", "nomenclature": "Airframe De-Icing"},
  {"code": "13400", "nomenclature": "Airframe Systems, Components, and Accessories (General)"},
  {"code": "13030", "nomenclature": "Airworthiness and Service Suitability"},
  {"code": "2222", "nomenclature": "AJ (Anti-Jamming)"},
  {"code": "5353", "nomenclature": "Alcohol Abuse Control (Civilian and Military)"},
  {"code": "2043", "nomenclature": "Alerting Net (JCS)"},
  {"code": "3720", "nomenclature": "All Weather Flying"},
  {"code": "3213", "nomenclature": "Allied Efforts (SIGINT)"},
  {"code": "3512", "nomenclature": "Allied Tactical Publications"},
  {"code": "2410", "nomenclature": "Allocation/Assignment (Electromagnetic Spectrum)"},
  {"code": "5321", "nomenclature": "Allocations and Ceilings"},
  {"code": "7620", "nomenclature": "Allocations, Cash (Industrial Fund Financing)"},
  {"code": "4832", "nomenclature": "Allocations, Materials (Controlled and Uncontrolled)"},
  {"code": "7303", "nomenclature": "Allotments and Project Orders"},
  {"code": "12595", "nomenclature": "Allowance, Physician's Comparability"},
  {"code": "8011", "nomenclature": "Allowance (Ammunition and Explosives)"},
  {"code": "4441", "nomenclature": "Allowances (Inventory Control)"},
  {"code": "7431", "nomenclature": "Allowances and Accounts (Military)"},
  {"code": "12591", "nomenclature": "Allowances and Differentials Payable in Non-Foreign Areas"},
  {"code": "12594", "nomenclature": "Allowances for Uniforms (Civilians)"},
  {"code": "2517", "nomenclature": "ALPS (AUTODIN Limited Privacy Service)"},
  {"code": "4720", "nomenclature": "Alterations and Improvements"},
  {"code": "12620", "nomenclature": "Alternative Work Schedules"},
  {"code": "2321", "nomenclature": "ALTROUTE"},
  {"code": "2093", "nomenclature": "Amateur Radio"},
  {"code": "6450", "nomenclature": "Ambulatory Care Medicine"},
  {"code": "5770", "nomenclature": "American Forces Radio &Television (AFRTS)"},
  {"code": "5760", "nomenclature": "American Red Cross (Organizations, Associations, and Societies)"},
  {"code": "8037", "nomenclature": "Ammunition (Aircraft Gun)"},
  {"code": "8020", "nomenclature": "Ammunition and Explosives Safety"},
  {"code": "8010", "nomenclature": "Ammunition and Explosives"},
  {"code": "8015", "nomenclature": "Ammunition Stock Recording Systems"},
  {"code": "7591", "nomenclature": "Amortization and Depreciation"},
  {"code": "3340", "nomenclature": "Amphibious (Warfare Procedures)"},
  {"code": "6440", "nomenclature": "Amphibious and Field Medicine"},
  {"code": "8061", "nomenclature": "Amphibious and Underwater Demolition Material"},
  {"code": "8440", "nomenclature": "Amphibious Vehicles"},
  {"code": "5223", "nomenclature": "Analysis and Review, Management"},
  {"code": "9581", "nomenclature": "Anchor Handling and Stowage Systems"},
  {"code": "3171", "nomenclature": "Anchorage and Berthing (Port Operations)"},
  {"code": "10570", "nomenclature": "Animals, Domestic and Wild"},
  {"code": "9405", "nomenclature": "Antenna Requirements"},
  {"code": "13450", "nomenclature": "Anti-Icing and Fogging"},
  {"code": "8146", "nomenclature": "Anti-Stealth"},
  {"code": "3312", "nomenclature": "Antisubmarine (Aerial) (Warfare Procedures)"},
  {"code": "13121", "nomenclature": "Antisubmarine (Fixed Wing Aircraft)"},
  {"code": "3360", "nomenclature": "Antisubmarine (Warfare Procedures)"},
  {"code": "8555", "nomenclature": "Antisubmarine Mine"},
  {"code": "13260", "nomenclature": "Antisubmarine Warfare (ASW) Systems (Avionics)"},
  {"code": "2086", "nomenclature": "Antisubmarine Warfare Broadcast System"},
  {"code": "2098", "nomenclature": "Antisubmarine Warfare Systems"},
  {"code": "8982", "nomenclature": "Anti-Swimmer Ordnance and Weapons Systems"},
  {"code": "7577", "nomenclature": "Appeal and Review Briefs"},
  {"code": "12772", "nomenclature": "Appeals to the Merit Systems Protection Board (MSPB)"},
  {"code": "7131", "nomenclature": "Apportionments/Allocations"},
  {"code": "3351", "nomenclature": "Approach and Attack Procedures (Submarine Warfare Procedures)"},
  {"code": "7301", "nomenclature": "Appropriation Accounting"},
  {"code": "7101", "nomenclature": "Appropriation Structure and Language"},
  {"code": "7300", "nomenclature": "Appropriation, Fund, Cost and Property Accounting (General)"},
  {"code": "7111", "nomenclature": "Appropriations, Regular (Budget/Estimate Preparation)"},
  {"code": "7040", "nomenclature": "Appropriations/Funding Specific"},
  {"code": "5753", "nomenclature": "Archives (Historical Matters)"},
  {"code": "9700", "nomenclature": "Armament (General)"},
  {"code": "8960", "nomenclature": "Armor (Ordnance Material)"},
  {"code": "3574", "nomenclature": "Arms, Small (Ordnance)"},
  {"code": "13430", "nomenclature": "Arresting and Launching, Aircraft Components for"},
  {"code": "5754", "nomenclature": "Artifacts and Paintings"},
  {"code": "8080", "nomenclature": "Artillery"},
  {"code": "2051", "nomenclature": "Ashore SATCOM Systems"},
  {"code": "8410", "nomenclature": "Assault Amphibian Vehicle (AAV)"},
  {"code": "8413", "nomenclature": "Assault Gun Vehicles"},
  {"code": "12275", "nomenclature": "Assessment of Personnel Programs (Civilian)"},
  {"code": "1336", "nomenclature": "Assignment and Distribution (Enlisted)"},
  {"code": "1300", "nomenclature": "Assignment and Distribution (General)"},
  {"code": "1301", "nomenclature": "Assignment and Distribution (Officer)"},
  {"code": "13300", "nomenclature": "Astronautic Vehicles (General)"},
  {"code": "3160", "nomenclature": "Astronomical and Chronometric Support"},
  {"code": "8832", "nomenclature": "ASW Standoff Weapon"},
  {"code": "10127", "nomenclature": "Atomic, Biological and Chemical Warfare Protective Clothing"},
  {"code": "13122", "nomenclature": "Attack Aircraft (Fixed Wing Aircraft)"},
  {"code": "12600", "nomenclature": "Attendance and Leave (General)"},
  {"code": "1154", "nomenclature": "Audio/Visual (Recruiting)"},
  {"code": "10700", "nomenclature": "Audiovisual Equipment and Accessories (General)"},
  {"code": "5290", "nomenclature": "Audiovisual Management (General)"},
  {"code": "7520", "nomenclature": "Audit Guide Programs"},
  {"code": "7564", "nomenclature": "Audit Liaison"},
  {"code": "7570", "nomenclature": "Audit Procedures, Contract"},
  {"code": "7511", "nomenclature": "Audit Schedules"},
  {"code": "7566", "nomenclature": "Audit Services for Other than DoD"},
  {"code": "7500", "nomenclature": "Auditing (General)"},
  {"code": "7510", "nomenclature": "Auditing, Internal"},
  {"code": "7502", "nomenclature": "Audits Conducted by the DoD Assistant Inspector General (Audit)"},
  {"code": "2071", "nomenclature": "AUTODIN I/AUTODIN II"},
  {"code": "5272", "nomenclature": "Automated Office Systems"},
  {"code": "2284", "nomenclature": "Automated Data Processing Support"},
  {"code": "9202", "nomenclature": "Automated Ship Control Systems"},
  {"code": "2020", "nomenclature": "Automated Systems (General)"},
  {"code": "13205", "nomenclature": "Automatic Carrier Landing System (Avionics)"},
  {"code": "5230", "nomenclature": "Automatic Data Processing and Information Systems"},
  {"code": "13223", "nomenclature": "Automatic Pilot Mechanisms and Airborne Gyro Components"},
  {"code": "2516", "nomenclature": "Automatic Processing System for SI Messages"},
  {"code": "13630", "nomenclature": "Automatic Test Equipment (Aeronautical Ground Support)"},
  {"code": "11240", "nomenclature": "Automotive (Transportation Facilities)"},
  {"code": "2074", "nomenclature": "AUTOSEVOCOM (and Successor Systems)"},
  {"code": "2073", "nomenclature": "AUTOVON"},
  {"code": "9517", "nomenclature": "Auxiliary Boilers"},
  {"code": "4623", "nomenclature": "Auxiliary Force Ships"},
  {"code": "9502", "nomenclature": "Auxiliary Machinery"},
  {"code": "9237", "nomenclature": "Auxiliary Propulsion Devices"},
  {"code": "9500", "nomenclature": "Auxiliary Systems (General)"},
  {"code": "12294", "nomenclature": "Availability of Official Information"},
  {"code": "10342", "nomenclature": "Aviation and General Purpose Fuels"},
  {"code": "1532", "nomenclature": "Aviation Cadet (AvCad)"},
  {"code": "6410", "nomenclature": "Aviation Medicine"},
  {"code": "8600", "nomenclature": "Aviation Ordnance (General)"},
  {"code": "5451", "nomenclature": "Aviation Shore Establishment"},
  {"code": "11130", "nomenclature": "Aviation Structures and Facilities"},
  {"code": "3770", "nomenclature": "Aviation, Civil"},
  {"code": "13200", "nomenclature": "Avionics (General)"},
  {"code": "13690", "nomenclature": "Avionics Support Equipment"},
  {"code": "12450", "nomenclature": "Awards (Civilian)"},
  {"code": "1650", "nomenclature": "Awards (Military)"},
  {"code": "5061", "nomenclature": "Awards (Public Service)"},
  {"code": "3590", "nomenclature": "Awards and Competitions (Training and Readiness)"},
  {"code": "5305", "nomenclature": "Awards, Incentive (Military/Civilian)"},
  {"code": "9191", "nomenclature": "Ballast and Buoyancy Units"},
  {"code": "9164", "nomenclature": "Ballistic Plating"},
  {"code": "8276", "nomenclature": "Ballistics (Gun and Missile Fire Control)"},
  {"code": "8226", "nomenclature": "Ballistics (Gun Fire Control)"},
  {"code": "5140", "nomenclature": "Band"},
  {"code": "5381", "nomenclature": "Banking Facilities and Credit Unions"},
  {"code": "12210", "nomenclature": "Basic Concepts and Definitions (General) (Civilian)"},
  {"code": "2804", "nomenclature": "Basic Electronics System Engineering Plan (BESEP)"},
  {"code": "8225", "nomenclature": "Battery Alignment (Gun Fire Control)"},
  {"code": "13280", "nomenclature": "Battery Systems"},
  {"code": "10420", "nomenclature": "Bearing"},
  {"code": "6321", "nomenclature": "Beds (Hospitalization)"}
]
