import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: 'Marine Corps Directives Formatter',
  description: 'Generated by Semper Admin',
};

function FeedbackButton() {
  return (
    <>
      <a
        href="https://semperadmin.github.io/Sentinel/#detail/marine-corps-directives-formatter/todo"
        className="feedback-btn"
        title="Share Feedback"
      >
        💬 Feedback
      </a>
      <style>{`
        .feedback-btn {
          position: fixed;
          bottom: 2rem;
          right: 2rem;
          background: linear-gradient(135deg, hsl(348, 83%, 47%) 0%, hsl(348, 83%, 37%) 100%);
          color: white;
          border: none;
          padding: 0.75rem 1.25rem;
          border-radius: 50px;
          font-size: 1rem;
          font-weight: 600;
          cursor: pointer;
          box-shadow: 0 4px 12px hsla(348, 83%, 47%, 0.3);
          transition: all 0.3s ease;
          z-index: 1000;
          display: flex;
          align-items: center;
          gap: 0.5rem;
          font-family: sans-serif;
          text-decoration: none;
        }

        .feedback-btn:hover {
          background: linear-gradient(135deg, hsl(348, 83%, 37%) 0%, hsl(348, 83%, 27%) 100%);
          box-shadow: 0 6px 16px hsla(348, 83%, 47%, 0.4);
          transform: translateY(-2px);
        }

        .feedback-btn:active {
          transform: translateY(0);
        }
      `}</style>
    </>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Roboto:wght@400;500;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        {children}
        <Toaster />
        <FeedbackButton />
      </body>
    </html>
  );
}
