#!/usr/bin/env node

/**
 * Fetch YouTube Videos and Save as Static Data
 *
 * This script fetches videos from the Semper Admin YouTube channel via the
 * YouTube Data API v3 and saves them as a static JavaScript file.
 *
 * This allows the frontend to load YouTube data WITHOUT making API calls,
 * preventing quota exhaustion from user traffic.
 *
 * Usage: node scripts/fetch-youtube.mjs
 * Environment: Requires YOUTUBE_API_KEY and YOUTUBE_CHANNEL_ID
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration
const YOUTUBE_API_KEY = process.env.YOUTUBE_API_KEY;
const YOUTUBE_CHANNEL_ID = process.env.YOUTUBE_CHANNEL_ID || 'UCob5u7jsXrdca9vmarYJ0Cg';
const MAX_PAGES = 5; // Fetch 5 pages × 50 videos = ~250 videos (500 quota units)
const RESULTS_PER_PAGE = 50;
const OUTPUT_FILE = path.join(__dirname, '../lib/youtube-data.js');

console.log('[YouTube] Starting fetch process...');
console.log(`[YouTube] Channel ID: ${YOUTUBE_CHANNEL_ID}`);
console.log(`[YouTube] Max pages: ${MAX_PAGES} (${MAX_PAGES * RESULTS_PER_PAGE} videos max)`);

// Validate API key
if (!YOUTUBE_API_KEY) {
  console.error('❌ CRITICAL: YOUTUBE_API_KEY environment variable is not set');
  console.error('   This script requires a YouTube Data API v3 key');
  console.error('   Get one at: https://console.cloud.google.com/');
  process.exit(1);
}

/**
 * Fetch YouTube videos using pagination
 */
async function fetchYouTubeVideos() {
  const allVideos = [];
  let pageToken = '';
  let pageCount = 0;

  try {
    while (pageCount < MAX_PAGES) {
      pageCount++;
      console.log(`[YouTube] Fetching page ${pageCount}/${MAX_PAGES}...`);

      // Build API URL
      const params = new URLSearchParams({
        part: 'snippet',
        channelId: YOUTUBE_CHANNEL_ID,
        maxResults: RESULTS_PER_PAGE.toString(),
        order: 'date',
        type: 'video',
        key: YOUTUBE_API_KEY
      });

      if (pageToken) {
        params.append('pageToken', pageToken);
      }

      const url = `https://www.googleapis.com/youtube/v3/search?${params.toString()}`;

      // Fetch from YouTube API
      const response = await fetch(url);

      if (!response.ok) {
        const errorText = await response.text();
        console.error(`❌ YouTube API error (${response.status}): ${errorText}`);
        break;
      }

      const data = await response.json();

      // Parse videos
      if (data.items && data.items.length > 0) {
        data.items.forEach(item => {
          if (item.id.videoId) {
            allVideos.push({
              id: item.id.videoId,
              title: item.snippet.title,
              description: item.snippet.description,
              publishedAt: item.snippet.publishedAt,
              thumbnail: item.snippet.thumbnails?.default?.url || '',
              channelTitle: item.snippet.channelTitle
            });
          }
        });

        console.log(`   Retrieved ${data.items.length} videos (total: ${allVideos.length})`);
      }

      // Get next page token
      pageToken = data.nextPageToken || '';

      // Stop if no more pages
      if (!pageToken || allVideos.length >= MAX_PAGES * RESULTS_PER_PAGE) {
        break;
      }
    }

    console.log(`[YouTube] ✓ Fetched ${allVideos.length} videos from ${pageCount} pages`);
    console.log(`[YouTube] Quota used: ${pageCount * 100} units (out of 10,000 daily limit)`);

    return allVideos;

  } catch (error) {
    console.error('[YouTube] Error fetching videos:', error.message);
    throw error;
  }
}

/**
 * Generate static JavaScript file with YouTube data
 */
function generateStaticFile(videos) {
  const timestamp = new Date().toISOString();

  const fileContent = `/**
 * YouTube Videos Data
 *
 * Auto-generated from Semper Admin YouTube channel
 * Source: https://www.youtube.com/@SemperAdmin
 * Channel ID: ${YOUTUBE_CHANNEL_ID}
 * Generated: ${timestamp}
 * Total Videos: ${videos.length}
 *
 * This file is automatically generated by scripts/fetch-youtube.mjs
 * DO NOT EDIT MANUALLY
 */

// YouTube video data structure
const YOUTUBE_VIDEOS = ${JSON.stringify(videos, null, 2)};

// Export for use in frontend (if using modules) or make globally available
if (typeof module !== 'undefined' && module.exports) {
  module.exports = YOUTUBE_VIDEOS;
}

// Make available globally for browser usage
if (typeof window !== 'undefined') {
  window.YOUTUBE_VIDEOS = YOUTUBE_VIDEOS;
}
`;

  return fileContent;
}

/**
 * Main execution
 */
async function main() {
  try {
    // Fetch videos
    const videos = await fetchYouTubeVideos();

    if (videos.length === 0) {
      console.warn('⚠️  No videos fetched - returning empty array (graceful degradation)');
    }

    // Generate static file
    console.log(`[YouTube] Generating static file: ${OUTPUT_FILE}`);
    const fileContent = generateStaticFile(videos);

    // Write to file
    await fs.writeFile(OUTPUT_FILE, fileContent, 'utf-8');
    console.log(`[YouTube] ✓ Data file written successfully`);

    // Display summary
    console.log('\n═══════════════════════════════════════════');
    console.log('  YouTube Data Fetch Complete');
    console.log('═══════════════════════════════════════════');
    console.log(`  Videos fetched: ${videos.length}`);
    console.log(`  Output file: ${path.relative(process.cwd(), OUTPUT_FILE)}`);
    console.log(`  Generated: ${new Date().toISOString()}`);
    console.log('═══════════════════════════════════════════\n');

    process.exit(0);

  } catch (error) {
    console.error('\n❌ Fatal error:', error);
    process.exit(1);
  }
}

// Run main function
main();
