/**
 * ALNAV Messages Data
 *
 * Generated based on known URL patterns from MyNavyHR Website
 * Source Pattern: https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN{YEAR}/ALN{YY}{NNN}.txt|pdf
 * Years Covered: 2023-2025 (2025, 2024, 2023)
 * Generated: 2026-01-15T06:28:28.844Z
 * Total Records: 170
 *
 * Note: This file is generated based on URL patterns. Some links may not be valid
 * if the Navy hasn't released that particular ALNAV yet.
 *
 * This file is automatically generated by scripts/generate-alnav-data.mjs
 * DO NOT EDIT MANUALLY
 */

// ALNAV messages data structure
const ALNAV_MESSAGES = [
  {
    "id": "ALNAV 045/25",
    "title": "ALNAV 045/25",
    "subject": "Navy All Hands Message 045/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25045.pdf",
    "pubDate": "2025-12-17T00:00:00.000Z",
    "description": "ALNAV 045/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 044/25",
    "title": "ALNAV 044/25",
    "subject": "Navy All Hands Message 044/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25044.txt",
    "pubDate": "2025-12-16T00:00:00.000Z",
    "description": "ALNAV 044/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 043/25",
    "title": "ALNAV 043/25",
    "subject": "Navy All Hands Message 043/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25043.txt",
    "pubDate": "2025-12-15T00:00:00.000Z",
    "description": "ALNAV 043/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 042/25",
    "title": "ALNAV 042/25",
    "subject": "Navy All Hands Message 042/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25042.pdf",
    "pubDate": "2025-11-14T00:00:00.000Z",
    "description": "ALNAV 042/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 041/25",
    "title": "ALNAV 041/25",
    "subject": "Navy All Hands Message 041/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25041.txt",
    "pubDate": "2025-11-13T00:00:00.000Z",
    "description": "ALNAV 041/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 040/25",
    "title": "ALNAV 040/25",
    "subject": "Navy All Hands Message 040/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25040.txt",
    "pubDate": "2025-11-12T00:00:00.000Z",
    "description": "ALNAV 040/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 039/25",
    "title": "ALNAV 039/25",
    "subject": "Navy All Hands Message 039/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25039.pdf",
    "pubDate": "2025-11-11T00:00:00.000Z",
    "description": "ALNAV 039/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 038/25",
    "title": "ALNAV 038/25",
    "subject": "Navy All Hands Message 038/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25038.txt",
    "pubDate": "2025-10-10T00:00:00.000Z",
    "description": "ALNAV 038/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 037/25",
    "title": "ALNAV 037/25",
    "subject": "Navy All Hands Message 037/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25037.txt",
    "pubDate": "2025-10-09T00:00:00.000Z",
    "description": "ALNAV 037/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 036/25",
    "title": "ALNAV 036/25",
    "subject": "Navy All Hands Message 036/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25036.pdf",
    "pubDate": "2025-10-08T00:00:00.000Z",
    "description": "ALNAV 036/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 035/25",
    "title": "ALNAV 035/25",
    "subject": "Navy All Hands Message 035/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25035.txt",
    "pubDate": "2025-10-07T00:00:00.000Z",
    "description": "ALNAV 035/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 034/25",
    "title": "ALNAV 034/25",
    "subject": "Navy All Hands Message 034/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25034.txt",
    "pubDate": "2025-09-06T00:00:00.000Z",
    "description": "ALNAV 034/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 033/25",
    "title": "ALNAV 033/25",
    "subject": "Navy All Hands Message 033/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25033.pdf",
    "pubDate": "2025-09-05T00:00:00.000Z",
    "description": "ALNAV 033/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 032/25",
    "title": "ALNAV 032/25",
    "subject": "Navy All Hands Message 032/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25032.txt",
    "pubDate": "2025-09-04T00:00:00.000Z",
    "description": "ALNAV 032/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 031/25",
    "title": "ALNAV 031/25",
    "subject": "Navy All Hands Message 031/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25031.txt",
    "pubDate": "2025-09-03T00:00:00.000Z",
    "description": "ALNAV 031/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 028/25",
    "title": "ALNAV 028/25",
    "subject": "Navy All Hands Message 028/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25028.txt",
    "pubDate": "2025-08-28T00:00:00.000Z",
    "description": "ALNAV 028/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 030/25",
    "title": "ALNAV 030/25",
    "subject": "Navy All Hands Message 030/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25030.pdf",
    "pubDate": "2025-08-02T00:00:00.000Z",
    "description": "ALNAV 030/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 029/25",
    "title": "ALNAV 029/25",
    "subject": "Navy All Hands Message 029/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25029.txt",
    "pubDate": "2025-08-01T00:00:00.000Z",
    "description": "ALNAV 029/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 027/25",
    "title": "ALNAV 027/25",
    "subject": "Navy All Hands Message 027/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25027.pdf",
    "pubDate": "2025-07-27T00:00:00.000Z",
    "description": "ALNAV 027/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 026/25",
    "title": "ALNAV 026/25",
    "subject": "Navy All Hands Message 026/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25026.txt",
    "pubDate": "2025-07-26T00:00:00.000Z",
    "description": "ALNAV 026/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 025/25",
    "title": "ALNAV 025/25",
    "subject": "Navy All Hands Message 025/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25025.txt",
    "pubDate": "2025-07-25T00:00:00.000Z",
    "description": "ALNAV 025/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 024/25",
    "title": "ALNAV 024/25",
    "subject": "Navy All Hands Message 024/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25024.pdf",
    "pubDate": "2025-07-24T00:00:00.000Z",
    "description": "ALNAV 024/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 023/25",
    "title": "ALNAV 023/25",
    "subject": "Navy All Hands Message 023/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25023.txt",
    "pubDate": "2025-06-23T00:00:00.000Z",
    "description": "ALNAV 023/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 022/25",
    "title": "ALNAV 022/25",
    "subject": "Navy All Hands Message 022/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25022.txt",
    "pubDate": "2025-06-22T00:00:00.000Z",
    "description": "ALNAV 022/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 021/25",
    "title": "ALNAV 021/25",
    "subject": "Navy All Hands Message 021/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25021.pdf",
    "pubDate": "2025-06-21T00:00:00.000Z",
    "description": "ALNAV 021/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 020/25",
    "title": "ALNAV 020/25",
    "subject": "Navy All Hands Message 020/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25020.txt",
    "pubDate": "2025-06-20T00:00:00.000Z",
    "description": "ALNAV 020/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 019/25",
    "title": "ALNAV 019/25",
    "subject": "Navy All Hands Message 019/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25019.txt",
    "pubDate": "2025-05-19T00:00:00.000Z",
    "description": "ALNAV 019/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 018/25",
    "title": "ALNAV 018/25",
    "subject": "Navy All Hands Message 018/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25018.pdf",
    "pubDate": "2025-05-18T00:00:00.000Z",
    "description": "ALNAV 018/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 017/25",
    "title": "ALNAV 017/25",
    "subject": "Navy All Hands Message 017/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25017.txt",
    "pubDate": "2025-05-17T00:00:00.000Z",
    "description": "ALNAV 017/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 016/25",
    "title": "ALNAV 016/25",
    "subject": "Navy All Hands Message 016/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25016.txt",
    "pubDate": "2025-05-16T00:00:00.000Z",
    "description": "ALNAV 016/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 015/25",
    "title": "ALNAV 015/25",
    "subject": "Navy All Hands Message 015/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25015.pdf",
    "pubDate": "2025-04-15T00:00:00.000Z",
    "description": "ALNAV 015/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 014/25",
    "title": "ALNAV 014/25",
    "subject": "Navy All Hands Message 014/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25014.txt",
    "pubDate": "2025-04-14T00:00:00.000Z",
    "description": "ALNAV 014/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 013/25",
    "title": "ALNAV 013/25",
    "subject": "Navy All Hands Message 013/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25013.txt",
    "pubDate": "2025-04-13T00:00:00.000Z",
    "description": "ALNAV 013/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 012/25",
    "title": "ALNAV 012/25",
    "subject": "Navy All Hands Message 012/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25012.pdf",
    "pubDate": "2025-03-12T00:00:00.000Z",
    "description": "ALNAV 012/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 011/25",
    "title": "ALNAV 011/25",
    "subject": "Navy All Hands Message 011/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25011.txt",
    "pubDate": "2025-03-11T00:00:00.000Z",
    "description": "ALNAV 011/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 010/25",
    "title": "ALNAV 010/25",
    "subject": "Navy All Hands Message 010/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25010.txt",
    "pubDate": "2025-03-10T00:00:00.000Z",
    "description": "ALNAV 010/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 009/25",
    "title": "ALNAV 009/25",
    "subject": "Navy All Hands Message 009/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25009.pdf",
    "pubDate": "2025-03-09T00:00:00.000Z",
    "description": "ALNAV 009/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 008/25",
    "title": "ALNAV 008/25",
    "subject": "Navy All Hands Message 008/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25008.txt",
    "pubDate": "2025-02-08T00:00:00.000Z",
    "description": "ALNAV 008/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 007/25",
    "title": "ALNAV 007/25",
    "subject": "Navy All Hands Message 007/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25007.txt",
    "pubDate": "2025-02-07T00:00:00.000Z",
    "description": "ALNAV 007/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 006/25",
    "title": "ALNAV 006/25",
    "subject": "Navy All Hands Message 006/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25006.pdf",
    "pubDate": "2025-02-06T00:00:00.000Z",
    "description": "ALNAV 006/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 005/25",
    "title": "ALNAV 005/25",
    "subject": "Navy All Hands Message 005/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25005.txt",
    "pubDate": "2025-02-05T00:00:00.000Z",
    "description": "ALNAV 005/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 004/25",
    "title": "ALNAV 004/25",
    "subject": "Navy All Hands Message 004/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25004.txt",
    "pubDate": "2025-01-04T00:00:00.000Z",
    "description": "ALNAV 004/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 003/25",
    "title": "ALNAV 003/25",
    "subject": "Navy All Hands Message 003/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25003.pdf",
    "pubDate": "2025-01-03T00:00:00.000Z",
    "description": "ALNAV 003/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 002/25",
    "title": "ALNAV 002/25",
    "subject": "Navy All Hands Message 002/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25002.txt",
    "pubDate": "2025-01-02T00:00:00.000Z",
    "description": "ALNAV 002/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 001/25",
    "title": "ALNAV 001/25",
    "subject": "Navy All Hands Message 001/25",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2025/ALN25001.txt",
    "pubDate": "2025-01-01T00:00:00.000Z",
    "description": "ALNAV 001/25 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 065/24",
    "title": "ALNAV 065/24",
    "subject": "Navy All Hands Message 065/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24065.txt",
    "pubDate": "2024-12-09T00:00:00.000Z",
    "description": "ALNAV 065/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 064/24",
    "title": "ALNAV 064/24",
    "subject": "Navy All Hands Message 064/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24064.txt",
    "pubDate": "2024-12-08T00:00:00.000Z",
    "description": "ALNAV 064/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 063/24",
    "title": "ALNAV 063/24",
    "subject": "Navy All Hands Message 063/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24063.pdf",
    "pubDate": "2024-12-07T00:00:00.000Z",
    "description": "ALNAV 063/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 062/24",
    "title": "ALNAV 062/24",
    "subject": "Navy All Hands Message 062/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24062.txt",
    "pubDate": "2024-12-06T00:00:00.000Z",
    "description": "ALNAV 062/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 061/24",
    "title": "ALNAV 061/24",
    "subject": "Navy All Hands Message 061/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24061.txt",
    "pubDate": "2024-12-05T00:00:00.000Z",
    "description": "ALNAV 061/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 056/24",
    "title": "ALNAV 056/24",
    "subject": "Navy All Hands Message 056/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24056.txt",
    "pubDate": "2024-11-28T00:00:00.000Z",
    "description": "ALNAV 056/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 060/24",
    "title": "ALNAV 060/24",
    "subject": "Navy All Hands Message 060/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24060.pdf",
    "pubDate": "2024-11-04T00:00:00.000Z",
    "description": "ALNAV 060/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 059/24",
    "title": "ALNAV 059/24",
    "subject": "Navy All Hands Message 059/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24059.txt",
    "pubDate": "2024-11-03T00:00:00.000Z",
    "description": "ALNAV 059/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 058/24",
    "title": "ALNAV 058/24",
    "subject": "Navy All Hands Message 058/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24058.txt",
    "pubDate": "2024-11-02T00:00:00.000Z",
    "description": "ALNAV 058/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 057/24",
    "title": "ALNAV 057/24",
    "subject": "Navy All Hands Message 057/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24057.pdf",
    "pubDate": "2024-11-01T00:00:00.000Z",
    "description": "ALNAV 057/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 055/24",
    "title": "ALNAV 055/24",
    "subject": "Navy All Hands Message 055/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24055.txt",
    "pubDate": "2024-10-27T00:00:00.000Z",
    "description": "ALNAV 055/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 054/24",
    "title": "ALNAV 054/24",
    "subject": "Navy All Hands Message 054/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24054.pdf",
    "pubDate": "2024-10-26T00:00:00.000Z",
    "description": "ALNAV 054/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 053/24",
    "title": "ALNAV 053/24",
    "subject": "Navy All Hands Message 053/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24053.txt",
    "pubDate": "2024-10-25T00:00:00.000Z",
    "description": "ALNAV 053/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 052/24",
    "title": "ALNAV 052/24",
    "subject": "Navy All Hands Message 052/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24052.txt",
    "pubDate": "2024-10-24T00:00:00.000Z",
    "description": "ALNAV 052/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 051/24",
    "title": "ALNAV 051/24",
    "subject": "Navy All Hands Message 051/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24051.pdf",
    "pubDate": "2024-10-23T00:00:00.000Z",
    "description": "ALNAV 051/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 050/24",
    "title": "ALNAV 050/24",
    "subject": "Navy All Hands Message 050/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24050.txt",
    "pubDate": "2024-10-22T00:00:00.000Z",
    "description": "ALNAV 050/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 049/24",
    "title": "ALNAV 049/24",
    "subject": "Navy All Hands Message 049/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24049.txt",
    "pubDate": "2024-09-21T00:00:00.000Z",
    "description": "ALNAV 049/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 048/24",
    "title": "ALNAV 048/24",
    "subject": "Navy All Hands Message 048/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24048.pdf",
    "pubDate": "2024-09-20T00:00:00.000Z",
    "description": "ALNAV 048/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 047/24",
    "title": "ALNAV 047/24",
    "subject": "Navy All Hands Message 047/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24047.txt",
    "pubDate": "2024-09-19T00:00:00.000Z",
    "description": "ALNAV 047/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 046/24",
    "title": "ALNAV 046/24",
    "subject": "Navy All Hands Message 046/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24046.txt",
    "pubDate": "2024-09-18T00:00:00.000Z",
    "description": "ALNAV 046/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 045/24",
    "title": "ALNAV 045/24",
    "subject": "Navy All Hands Message 045/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24045.pdf",
    "pubDate": "2024-09-17T00:00:00.000Z",
    "description": "ALNAV 045/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 044/24",
    "title": "ALNAV 044/24",
    "subject": "Navy All Hands Message 044/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24044.txt",
    "pubDate": "2024-08-16T00:00:00.000Z",
    "description": "ALNAV 044/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 043/24",
    "title": "ALNAV 043/24",
    "subject": "Navy All Hands Message 043/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24043.txt",
    "pubDate": "2024-08-15T00:00:00.000Z",
    "description": "ALNAV 043/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 042/24",
    "title": "ALNAV 042/24",
    "subject": "Navy All Hands Message 042/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24042.pdf",
    "pubDate": "2024-08-14T00:00:00.000Z",
    "description": "ALNAV 042/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 041/24",
    "title": "ALNAV 041/24",
    "subject": "Navy All Hands Message 041/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24041.txt",
    "pubDate": "2024-08-13T00:00:00.000Z",
    "description": "ALNAV 041/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 040/24",
    "title": "ALNAV 040/24",
    "subject": "Navy All Hands Message 040/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24040.txt",
    "pubDate": "2024-08-12T00:00:00.000Z",
    "description": "ALNAV 040/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 039/24",
    "title": "ALNAV 039/24",
    "subject": "Navy All Hands Message 039/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24039.pdf",
    "pubDate": "2024-08-11T00:00:00.000Z",
    "description": "ALNAV 039/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 038/24",
    "title": "ALNAV 038/24",
    "subject": "Navy All Hands Message 038/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24038.txt",
    "pubDate": "2024-07-10T00:00:00.000Z",
    "description": "ALNAV 038/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 037/24",
    "title": "ALNAV 037/24",
    "subject": "Navy All Hands Message 037/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24037.txt",
    "pubDate": "2024-07-09T00:00:00.000Z",
    "description": "ALNAV 037/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 036/24",
    "title": "ALNAV 036/24",
    "subject": "Navy All Hands Message 036/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24036.pdf",
    "pubDate": "2024-07-08T00:00:00.000Z",
    "description": "ALNAV 036/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 035/24",
    "title": "ALNAV 035/24",
    "subject": "Navy All Hands Message 035/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24035.txt",
    "pubDate": "2024-07-07T00:00:00.000Z",
    "description": "ALNAV 035/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 034/24",
    "title": "ALNAV 034/24",
    "subject": "Navy All Hands Message 034/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24034.txt",
    "pubDate": "2024-07-06T00:00:00.000Z",
    "description": "ALNAV 034/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 033/24",
    "title": "ALNAV 033/24",
    "subject": "Navy All Hands Message 033/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24033.pdf",
    "pubDate": "2024-06-05T00:00:00.000Z",
    "description": "ALNAV 033/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 032/24",
    "title": "ALNAV 032/24",
    "subject": "Navy All Hands Message 032/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24032.txt",
    "pubDate": "2024-06-04T00:00:00.000Z",
    "description": "ALNAV 032/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 031/24",
    "title": "ALNAV 031/24",
    "subject": "Navy All Hands Message 031/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24031.txt",
    "pubDate": "2024-06-03T00:00:00.000Z",
    "description": "ALNAV 031/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 030/24",
    "title": "ALNAV 030/24",
    "subject": "Navy All Hands Message 030/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24030.pdf",
    "pubDate": "2024-06-02T00:00:00.000Z",
    "description": "ALNAV 030/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 029/24",
    "title": "ALNAV 029/24",
    "subject": "Navy All Hands Message 029/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24029.txt",
    "pubDate": "2024-06-01T00:00:00.000Z",
    "description": "ALNAV 029/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 028/24",
    "title": "ALNAV 028/24",
    "subject": "Navy All Hands Message 028/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24028.txt",
    "pubDate": "2024-05-28T00:00:00.000Z",
    "description": "ALNAV 028/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 027/24",
    "title": "ALNAV 027/24",
    "subject": "Navy All Hands Message 027/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24027.pdf",
    "pubDate": "2024-05-27T00:00:00.000Z",
    "description": "ALNAV 027/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 026/24",
    "title": "ALNAV 026/24",
    "subject": "Navy All Hands Message 026/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24026.txt",
    "pubDate": "2024-05-26T00:00:00.000Z",
    "description": "ALNAV 026/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 025/24",
    "title": "ALNAV 025/24",
    "subject": "Navy All Hands Message 025/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24025.txt",
    "pubDate": "2024-05-25T00:00:00.000Z",
    "description": "ALNAV 025/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 024/24",
    "title": "ALNAV 024/24",
    "subject": "Navy All Hands Message 024/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24024.pdf",
    "pubDate": "2024-05-24T00:00:00.000Z",
    "description": "ALNAV 024/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 023/24",
    "title": "ALNAV 023/24",
    "subject": "Navy All Hands Message 023/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24023.txt",
    "pubDate": "2024-05-23T00:00:00.000Z",
    "description": "ALNAV 023/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 022/24",
    "title": "ALNAV 022/24",
    "subject": "Navy All Hands Message 022/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24022.txt",
    "pubDate": "2024-04-22T00:00:00.000Z",
    "description": "ALNAV 022/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 021/24",
    "title": "ALNAV 021/24",
    "subject": "Navy All Hands Message 021/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24021.pdf",
    "pubDate": "2024-04-21T00:00:00.000Z",
    "description": "ALNAV 021/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 020/24",
    "title": "ALNAV 020/24",
    "subject": "Navy All Hands Message 020/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24020.txt",
    "pubDate": "2024-04-20T00:00:00.000Z",
    "description": "ALNAV 020/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 019/24",
    "title": "ALNAV 019/24",
    "subject": "Navy All Hands Message 019/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24019.txt",
    "pubDate": "2024-04-19T00:00:00.000Z",
    "description": "ALNAV 019/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 018/24",
    "title": "ALNAV 018/24",
    "subject": "Navy All Hands Message 018/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24018.pdf",
    "pubDate": "2024-04-18T00:00:00.000Z",
    "description": "ALNAV 018/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 017/24",
    "title": "ALNAV 017/24",
    "subject": "Navy All Hands Message 017/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24017.txt",
    "pubDate": "2024-03-17T00:00:00.000Z",
    "description": "ALNAV 017/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 016/24",
    "title": "ALNAV 016/24",
    "subject": "Navy All Hands Message 016/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24016.txt",
    "pubDate": "2024-03-16T00:00:00.000Z",
    "description": "ALNAV 016/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 015/24",
    "title": "ALNAV 015/24",
    "subject": "Navy All Hands Message 015/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24015.pdf",
    "pubDate": "2024-03-15T00:00:00.000Z",
    "description": "ALNAV 015/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 014/24",
    "title": "ALNAV 014/24",
    "subject": "Navy All Hands Message 014/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24014.txt",
    "pubDate": "2024-03-14T00:00:00.000Z",
    "description": "ALNAV 014/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 013/24",
    "title": "ALNAV 013/24",
    "subject": "Navy All Hands Message 013/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24013.txt",
    "pubDate": "2024-03-13T00:00:00.000Z",
    "description": "ALNAV 013/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 012/24",
    "title": "ALNAV 012/24",
    "subject": "Navy All Hands Message 012/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24012.pdf",
    "pubDate": "2024-03-12T00:00:00.000Z",
    "description": "ALNAV 012/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 011/24",
    "title": "ALNAV 011/24",
    "subject": "Navy All Hands Message 011/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24011.txt",
    "pubDate": "2024-02-11T00:00:00.000Z",
    "description": "ALNAV 011/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 010/24",
    "title": "ALNAV 010/24",
    "subject": "Navy All Hands Message 010/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24010.txt",
    "pubDate": "2024-02-10T00:00:00.000Z",
    "description": "ALNAV 010/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 009/24",
    "title": "ALNAV 009/24",
    "subject": "Navy All Hands Message 009/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24009.pdf",
    "pubDate": "2024-02-09T00:00:00.000Z",
    "description": "ALNAV 009/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 008/24",
    "title": "ALNAV 008/24",
    "subject": "Navy All Hands Message 008/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24008.txt",
    "pubDate": "2024-02-08T00:00:00.000Z",
    "description": "ALNAV 008/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 007/24",
    "title": "ALNAV 007/24",
    "subject": "Navy All Hands Message 007/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24007.txt",
    "pubDate": "2024-02-07T00:00:00.000Z",
    "description": "ALNAV 007/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 006/24",
    "title": "ALNAV 006/24",
    "subject": "Navy All Hands Message 006/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24006.pdf",
    "pubDate": "2024-01-06T00:00:00.000Z",
    "description": "ALNAV 006/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 005/24",
    "title": "ALNAV 005/24",
    "subject": "Navy All Hands Message 005/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24005.txt",
    "pubDate": "2024-01-05T00:00:00.000Z",
    "description": "ALNAV 005/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 004/24",
    "title": "ALNAV 004/24",
    "subject": "Navy All Hands Message 004/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24004.txt",
    "pubDate": "2024-01-04T00:00:00.000Z",
    "description": "ALNAV 004/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 003/24",
    "title": "ALNAV 003/24",
    "subject": "Navy All Hands Message 003/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24003.pdf",
    "pubDate": "2024-01-03T00:00:00.000Z",
    "description": "ALNAV 003/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 002/24",
    "title": "ALNAV 002/24",
    "subject": "Navy All Hands Message 002/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24002.txt",
    "pubDate": "2024-01-02T00:00:00.000Z",
    "description": "ALNAV 002/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 001/24",
    "title": "ALNAV 001/24",
    "subject": "Navy All Hands Message 001/24",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2024/ALN24001.txt",
    "pubDate": "2024-01-01T00:00:00.000Z",
    "description": "ALNAV 001/24 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 056/23",
    "title": "ALNAV 056/23",
    "subject": "Navy All Hands Message 056/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23056.txt",
    "pubDate": "2023-12-28T00:00:00.000Z",
    "description": "ALNAV 056/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 060/23",
    "title": "ALNAV 060/23",
    "subject": "Navy All Hands Message 060/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23060.pdf",
    "pubDate": "2023-12-04T00:00:00.000Z",
    "description": "ALNAV 060/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 059/23",
    "title": "ALNAV 059/23",
    "subject": "Navy All Hands Message 059/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23059.txt",
    "pubDate": "2023-12-03T00:00:00.000Z",
    "description": "ALNAV 059/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 058/23",
    "title": "ALNAV 058/23",
    "subject": "Navy All Hands Message 058/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23058.txt",
    "pubDate": "2023-12-02T00:00:00.000Z",
    "description": "ALNAV 058/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 057/23",
    "title": "ALNAV 057/23",
    "subject": "Navy All Hands Message 057/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23057.pdf",
    "pubDate": "2023-12-01T00:00:00.000Z",
    "description": "ALNAV 057/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 055/23",
    "title": "ALNAV 055/23",
    "subject": "Navy All Hands Message 055/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23055.txt",
    "pubDate": "2023-11-27T00:00:00.000Z",
    "description": "ALNAV 055/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 054/23",
    "title": "ALNAV 054/23",
    "subject": "Navy All Hands Message 054/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23054.pdf",
    "pubDate": "2023-11-26T00:00:00.000Z",
    "description": "ALNAV 054/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 053/23",
    "title": "ALNAV 053/23",
    "subject": "Navy All Hands Message 053/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23053.txt",
    "pubDate": "2023-11-25T00:00:00.000Z",
    "description": "ALNAV 053/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 052/23",
    "title": "ALNAV 052/23",
    "subject": "Navy All Hands Message 052/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23052.txt",
    "pubDate": "2023-11-24T00:00:00.000Z",
    "description": "ALNAV 052/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 051/23",
    "title": "ALNAV 051/23",
    "subject": "Navy All Hands Message 051/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23051.pdf",
    "pubDate": "2023-11-23T00:00:00.000Z",
    "description": "ALNAV 051/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 050/23",
    "title": "ALNAV 050/23",
    "subject": "Navy All Hands Message 050/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23050.txt",
    "pubDate": "2023-10-22T00:00:00.000Z",
    "description": "ALNAV 050/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 049/23",
    "title": "ALNAV 049/23",
    "subject": "Navy All Hands Message 049/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23049.txt",
    "pubDate": "2023-10-21T00:00:00.000Z",
    "description": "ALNAV 049/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 048/23",
    "title": "ALNAV 048/23",
    "subject": "Navy All Hands Message 048/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23048.pdf",
    "pubDate": "2023-10-20T00:00:00.000Z",
    "description": "ALNAV 048/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 047/23",
    "title": "ALNAV 047/23",
    "subject": "Navy All Hands Message 047/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23047.txt",
    "pubDate": "2023-10-19T00:00:00.000Z",
    "description": "ALNAV 047/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 046/23",
    "title": "ALNAV 046/23",
    "subject": "Navy All Hands Message 046/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23046.txt",
    "pubDate": "2023-10-18T00:00:00.000Z",
    "description": "ALNAV 046/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 045/23",
    "title": "ALNAV 045/23",
    "subject": "Navy All Hands Message 045/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23045.pdf",
    "pubDate": "2023-09-17T00:00:00.000Z",
    "description": "ALNAV 045/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 044/23",
    "title": "ALNAV 044/23",
    "subject": "Navy All Hands Message 044/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23044.txt",
    "pubDate": "2023-09-16T00:00:00.000Z",
    "description": "ALNAV 044/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 043/23",
    "title": "ALNAV 043/23",
    "subject": "Navy All Hands Message 043/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23043.txt",
    "pubDate": "2023-09-15T00:00:00.000Z",
    "description": "ALNAV 043/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 042/23",
    "title": "ALNAV 042/23",
    "subject": "Navy All Hands Message 042/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23042.pdf",
    "pubDate": "2023-09-14T00:00:00.000Z",
    "description": "ALNAV 042/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 041/23",
    "title": "ALNAV 041/23",
    "subject": "Navy All Hands Message 041/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23041.txt",
    "pubDate": "2023-09-13T00:00:00.000Z",
    "description": "ALNAV 041/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 040/23",
    "title": "ALNAV 040/23",
    "subject": "Navy All Hands Message 040/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23040.txt",
    "pubDate": "2023-08-12T00:00:00.000Z",
    "description": "ALNAV 040/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 039/23",
    "title": "ALNAV 039/23",
    "subject": "Navy All Hands Message 039/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23039.pdf",
    "pubDate": "2023-08-11T00:00:00.000Z",
    "description": "ALNAV 039/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 038/23",
    "title": "ALNAV 038/23",
    "subject": "Navy All Hands Message 038/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23038.txt",
    "pubDate": "2023-08-10T00:00:00.000Z",
    "description": "ALNAV 038/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 037/23",
    "title": "ALNAV 037/23",
    "subject": "Navy All Hands Message 037/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23037.txt",
    "pubDate": "2023-08-09T00:00:00.000Z",
    "description": "ALNAV 037/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 036/23",
    "title": "ALNAV 036/23",
    "subject": "Navy All Hands Message 036/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23036.pdf",
    "pubDate": "2023-08-08T00:00:00.000Z",
    "description": "ALNAV 036/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 035/23",
    "title": "ALNAV 035/23",
    "subject": "Navy All Hands Message 035/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23035.txt",
    "pubDate": "2023-07-07T00:00:00.000Z",
    "description": "ALNAV 035/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 034/23",
    "title": "ALNAV 034/23",
    "subject": "Navy All Hands Message 034/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23034.txt",
    "pubDate": "2023-07-06T00:00:00.000Z",
    "description": "ALNAV 034/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 033/23",
    "title": "ALNAV 033/23",
    "subject": "Navy All Hands Message 033/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23033.pdf",
    "pubDate": "2023-07-05T00:00:00.000Z",
    "description": "ALNAV 033/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 032/23",
    "title": "ALNAV 032/23",
    "subject": "Navy All Hands Message 032/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23032.txt",
    "pubDate": "2023-07-04T00:00:00.000Z",
    "description": "ALNAV 032/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 031/23",
    "title": "ALNAV 031/23",
    "subject": "Navy All Hands Message 031/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23031.txt",
    "pubDate": "2023-07-03T00:00:00.000Z",
    "description": "ALNAV 031/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 028/23",
    "title": "ALNAV 028/23",
    "subject": "Navy All Hands Message 028/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23028.txt",
    "pubDate": "2023-06-28T00:00:00.000Z",
    "description": "ALNAV 028/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 027/23",
    "title": "ALNAV 027/23",
    "subject": "Navy All Hands Message 027/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23027.pdf",
    "pubDate": "2023-06-27T00:00:00.000Z",
    "description": "ALNAV 027/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 026/23",
    "title": "ALNAV 026/23",
    "subject": "Navy All Hands Message 026/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23026.txt",
    "pubDate": "2023-06-26T00:00:00.000Z",
    "description": "ALNAV 026/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 030/23",
    "title": "ALNAV 030/23",
    "subject": "Navy All Hands Message 030/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23030.pdf",
    "pubDate": "2023-06-02T00:00:00.000Z",
    "description": "ALNAV 030/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 029/23",
    "title": "ALNAV 029/23",
    "subject": "Navy All Hands Message 029/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23029.txt",
    "pubDate": "2023-06-01T00:00:00.000Z",
    "description": "ALNAV 029/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 025/23",
    "title": "ALNAV 025/23",
    "subject": "Navy All Hands Message 025/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23025.txt",
    "pubDate": "2023-05-25T00:00:00.000Z",
    "description": "ALNAV 025/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 024/23",
    "title": "ALNAV 024/23",
    "subject": "Navy All Hands Message 024/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23024.pdf",
    "pubDate": "2023-05-24T00:00:00.000Z",
    "description": "ALNAV 024/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 023/23",
    "title": "ALNAV 023/23",
    "subject": "Navy All Hands Message 023/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23023.txt",
    "pubDate": "2023-05-23T00:00:00.000Z",
    "description": "ALNAV 023/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 022/23",
    "title": "ALNAV 022/23",
    "subject": "Navy All Hands Message 022/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23022.txt",
    "pubDate": "2023-05-22T00:00:00.000Z",
    "description": "ALNAV 022/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 021/23",
    "title": "ALNAV 021/23",
    "subject": "Navy All Hands Message 021/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23021.pdf",
    "pubDate": "2023-05-21T00:00:00.000Z",
    "description": "ALNAV 021/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 020/23",
    "title": "ALNAV 020/23",
    "subject": "Navy All Hands Message 020/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23020.txt",
    "pubDate": "2023-04-20T00:00:00.000Z",
    "description": "ALNAV 020/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 019/23",
    "title": "ALNAV 019/23",
    "subject": "Navy All Hands Message 019/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23019.txt",
    "pubDate": "2023-04-19T00:00:00.000Z",
    "description": "ALNAV 019/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 018/23",
    "title": "ALNAV 018/23",
    "subject": "Navy All Hands Message 018/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23018.pdf",
    "pubDate": "2023-04-18T00:00:00.000Z",
    "description": "ALNAV 018/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 017/23",
    "title": "ALNAV 017/23",
    "subject": "Navy All Hands Message 017/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23017.txt",
    "pubDate": "2023-04-17T00:00:00.000Z",
    "description": "ALNAV 017/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 016/23",
    "title": "ALNAV 016/23",
    "subject": "Navy All Hands Message 016/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23016.txt",
    "pubDate": "2023-04-16T00:00:00.000Z",
    "description": "ALNAV 016/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 015/23",
    "title": "ALNAV 015/23",
    "subject": "Navy All Hands Message 015/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23015.pdf",
    "pubDate": "2023-03-15T00:00:00.000Z",
    "description": "ALNAV 015/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 014/23",
    "title": "ALNAV 014/23",
    "subject": "Navy All Hands Message 014/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23014.txt",
    "pubDate": "2023-03-14T00:00:00.000Z",
    "description": "ALNAV 014/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 013/23",
    "title": "ALNAV 013/23",
    "subject": "Navy All Hands Message 013/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23013.txt",
    "pubDate": "2023-03-13T00:00:00.000Z",
    "description": "ALNAV 013/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 012/23",
    "title": "ALNAV 012/23",
    "subject": "Navy All Hands Message 012/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23012.pdf",
    "pubDate": "2023-03-12T00:00:00.000Z",
    "description": "ALNAV 012/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 011/23",
    "title": "ALNAV 011/23",
    "subject": "Navy All Hands Message 011/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23011.txt",
    "pubDate": "2023-03-11T00:00:00.000Z",
    "description": "ALNAV 011/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 010/23",
    "title": "ALNAV 010/23",
    "subject": "Navy All Hands Message 010/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23010.txt",
    "pubDate": "2023-02-10T00:00:00.000Z",
    "description": "ALNAV 010/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 009/23",
    "title": "ALNAV 009/23",
    "subject": "Navy All Hands Message 009/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23009.pdf",
    "pubDate": "2023-02-09T00:00:00.000Z",
    "description": "ALNAV 009/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 008/23",
    "title": "ALNAV 008/23",
    "subject": "Navy All Hands Message 008/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23008.txt",
    "pubDate": "2023-02-08T00:00:00.000Z",
    "description": "ALNAV 008/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 007/23",
    "title": "ALNAV 007/23",
    "subject": "Navy All Hands Message 007/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23007.txt",
    "pubDate": "2023-02-07T00:00:00.000Z",
    "description": "ALNAV 007/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 006/23",
    "title": "ALNAV 006/23",
    "subject": "Navy All Hands Message 006/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23006.pdf",
    "pubDate": "2023-02-06T00:00:00.000Z",
    "description": "ALNAV 006/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 005/23",
    "title": "ALNAV 005/23",
    "subject": "Navy All Hands Message 005/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23005.txt",
    "pubDate": "2023-01-05T00:00:00.000Z",
    "description": "ALNAV 005/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 004/23",
    "title": "ALNAV 004/23",
    "subject": "Navy All Hands Message 004/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23004.txt",
    "pubDate": "2023-01-04T00:00:00.000Z",
    "description": "ALNAV 004/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 003/23",
    "title": "ALNAV 003/23",
    "subject": "Navy All Hands Message 003/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23003.pdf",
    "pubDate": "2023-01-03T00:00:00.000Z",
    "description": "ALNAV 003/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 002/23",
    "title": "ALNAV 002/23",
    "subject": "Navy All Hands Message 002/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23002.txt",
    "pubDate": "2023-01-02T00:00:00.000Z",
    "description": "ALNAV 002/23 - Navy-wide administrative message"
  },
  {
    "id": "ALNAV 001/23",
    "title": "ALNAV 001/23",
    "subject": "Navy All Hands Message 001/23",
    "link": "https://www.mynavyhr.navy.mil/Portals/55/Messages/ALNAV/ALN2023/ALN23001.txt",
    "pubDate": "2023-01-01T00:00:00.000Z",
    "description": "ALNAV 001/23 - Navy-wide administrative message"
  }
];

// Metadata
const ALNAV_META = {
  sourceUrls: ['https://www.mynavyhr.navy.mil/References/Messages/ALNAV-2025/', 'https://www.mynavyhr.navy.mil/References/Messages/ALNAV-2024/', 'https://www.mynavyhr.navy.mil/References/Messages/ALNAV-2023/'],
  yearsFetched: [2025, 2024, 2023],
  yearRange: '2023-2025',
  generatedAt: '2026-01-15T06:28:28.844Z',
  totalRecords: 170,
  note: 'Generated from URL patterns - some links may not be active yet'
};

// Export for use in application
if (typeof window !== 'undefined') {
  window.ALNAV_MESSAGES = ALNAV_MESSAGES;
  window.ALNAV_META = ALNAV_META;
}

// Also support module exports for testing
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    ALNAV_MESSAGES,
    ALNAV_META
  };
}
