/**
 * YouTube Videos Data
 *
 * Auto-generated from Semper Admin YouTube channel
 * Source: https://www.youtube.com/@SemperAdmin
 * Channel ID: UCob5u7jsXrdca9vmarYJ0Cg
 * Generated: 2026-01-15T11:17:17.251Z
 * Total Videos: 25
 *
 * This file is automatically generated by scripts/fetch-youtube.mjs
 * DO NOT EDIT MANUALLY
 */

// YouTube video data structure
const YOUTUBE_VIDEOS = [
  {
    "id": "yfLg5RJM8Fo",
    "title": "Large Language Models: Processing MARADMIN Action Items",
    "description": "In this tutorial, learn how to use DoD-approved AI tools extracting action items from MARADMINs enabling immediate compliance ...",
    "publishedAt": "2026-01-14T10:01:43Z",
    "thumbnail": "https://i.ytimg.com/vi/yfLg5RJM8Fo/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "8S-1fCtavEk",
    "title": "Large Language Models: Preparing Briefing Outlines and Talking Points",
    "description": "In this tutorial, learn how to use DoD-approved AI tools preparing briefing outlines and talking points organizing raw information ...",
    "publishedAt": "2026-01-12T10:00:20Z",
    "thumbnail": "https://i.ytimg.com/vi/8S-1fCtavEk/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "CnwJn6nJpgA",
    "title": "Large Language Models: Creating POA&amp;Ms and Training Schedules",
    "description": "In this tutorial, learn how to use DoD-approved AI tools building POA&Ms and training schedules generating draft plans in minutes ...",
    "publishedAt": "2026-01-09T10:00:18Z",
    "thumbnail": "https://i.ytimg.com/vi/CnwJn6nJpgA/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "C_KPB2r2XBc",
    "title": "Large Language Models: Explaining Complex Regulations in Plain Language",
    "description": "In this tutorial, learn how to use DoD-approved AI tools translating complex regulations into plain language ensuring you and your ...",
    "publishedAt": "2026-01-07T10:00:18Z",
    "thumbnail": "https://i.ytimg.com/vi/C_KPB2r2XBc/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "9HY_fQNO8eE",
    "title": "Large Language Models: Writing Counseling Statements and Page 11 Entries",
    "description": "In this tutorial, learn how to use DoD-approved AI tools drafting counseling statements and Page 11 entries converting ...",
    "publishedAt": "2026-01-05T10:00:13Z",
    "thumbnail": "https://i.ytimg.com/vi/9HY_fQNO8eE/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "EpwFf8s3GIw",
    "title": "Large Language Models: Summarizing Long Policy Documents",
    "description": "In this tutorial, learn how to use DoD-approved AI tools summarizing MARADMINs and policy documents extracting key points in ...",
    "publishedAt": "2026-01-02T10:00:23Z",
    "thumbnail": "https://i.ytimg.com/vi/EpwFf8s3GIw/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "eZmvAOsgOqE",
    "title": "Large Language Models: Drafting Professional Emails in Seconds",
    "description": "In this tutorial, learn how to use DoD-approved AI tools transforming bullet points into polished professional correspondence in ...",
    "publishedAt": "2025-12-31T10:01:10Z",
    "thumbnail": "https://i.ytimg.com/vi/eZmvAOsgOqE/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "2cVS6oXdWZs",
    "title": "Promotions: Promotion Folder Part 6 - Miscellaneous",
    "description": "In this tutorial, learn the comprehensive Promotion Folder Part 6 requirements documenting miscellaneous cases handling ...",
    "publishedAt": "2025-12-29T10:00:04Z",
    "thumbnail": "https://i.ytimg.com/vi/2cVS6oXdWZs/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Lj3jhwyqKVE",
    "title": "Promotions: Promotion Folder Part 5 - Not Recommended After Select Grade",
    "description": "In this tutorial, learn the comprehensive Promotion Folder Part 5 requirements documenting not recommended after select grade ...",
    "publishedAt": "2025-12-26T10:00:38Z",
    "thumbnail": "https://i.ytimg.com/vi/Lj3jhwyqKVE/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "sgnCngRQ6Us",
    "title": "Promotions: Promotion Folder Part 4 - Select Grade Documentation",
    "description": "In this tutorial, learn the comprehensive Promotion Folder Part 4 requirements documenting promotion execution proving proper ...",
    "publishedAt": "2025-12-24T10:01:37Z",
    "thumbnail": "https://i.ytimg.com/vi/sgnCngRQ6Us/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "vUiKA-jW1SA",
    "title": "Promotions: Promotion Folder Part 3 - Promotion Authority",
    "description": "In this tutorial, learn the comprehensive Promotion Folder Part 3 requirements documenting promotion authority proving legal ...",
    "publishedAt": "2025-12-22T10:01:38Z",
    "thumbnail": "https://i.ytimg.com/vi/vUiKA-jW1SA/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "lvwtZ-v1sNU",
    "title": "Promotions: Promotion Folder Part 2 - Recommendation Rosters",
    "description": "In this tutorial, learn the comprehensive Promotion Folder Part 2 requirements documenting recommendation processing through ...",
    "publishedAt": "2025-12-19T10:01:24Z",
    "thumbnail": "https://i.ytimg.com/vi/lvwtZ-v1sNU/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "u1RQjABRh1s",
    "title": "Promotions: Promotion Folder Part 1 - Missing Training and JEPES Occasions",
    "description": "In this tutorial, learn the comprehensive Promotion Folder Part 1 requirements documenting training accountability and JEPES ...",
    "publishedAt": "2025-12-17T10:01:33Z",
    "thumbnail": "https://i.ytimg.com/vi/u1RQjABRh1s/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "xkF5bUy349s",
    "title": "Promotions: Understanding the Promotion Folder",
    "description": "In this tutorial, learn the comprehensive promotion folder organizational structure and purpose maintaining proper promotion ...",
    "publishedAt": "2025-12-15T10:01:32Z",
    "thumbnail": "https://i.ytimg.com/vi/xkF5bUy349s/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "l1emYAOT8HY",
    "title": "Separations and Retirement: Post-Retirement (0-12 Months)",
    "description": "In this tutorial, learn the comprehensive post-retirement phase spanning 0-12 months after separation that establishes civilian life ...",
    "publishedAt": "2025-12-12T10:01:28Z",
    "thumbnail": "https://i.ytimg.com/vi/l1emYAOT8HY/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Eh6X7LWx0Ow",
    "title": "Separations and Retirement: Final Phase (Month of Retirement)",
    "description": "In this tutorial, learn the comprehensive final phase during month of retirement that completes active duty service through ...",
    "publishedAt": "2025-12-10T10:00:32Z",
    "thumbnail": "https://i.ytimg.com/vi/Eh6X7LWx0Ow/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Jk0mU_vhf4I",
    "title": "Separations and Retirement: Final Preparations &amp; Outprocessing (2-0 Months)",
    "description": "In this tutorial, learn the comprehensive final preparations and outprocessing phase spanning months 2-0 before separation that ...",
    "publishedAt": "2025-12-08T10:00:27Z",
    "thumbnail": "https://i.ytimg.com/vi/Jk0mU_vhf4I/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "UXrZ3IHkM-I",
    "title": "Separations and Retirement: Documentation, Legal &amp; Ceremony Planning (4-2 Months)",
    "description": "In this tutorial, learn the comprehensive documentation, legal, and ceremony planning phase spanning months 4-2 before ...",
    "publishedAt": "2025-12-05T10:01:01Z",
    "thumbnail": "https://i.ytimg.com/vi/UXrZ3IHkM-I/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "2H6boXQ4Tkg",
    "title": "Separations and Retirement: Job Search &amp; Medical Readiness (6-4 Months)",
    "description": "In this tutorial, learn the comprehensive job search and medical readiness phase spanning months 6-4 before separation that ...",
    "publishedAt": "2025-12-03T10:00:06Z",
    "thumbnail": "https://i.ytimg.com/vi/2H6boXQ4Tkg/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Epb4oNH6Phk",
    "title": "Separations and Retirement: Financial, Family &amp; Terminal Leave Planning (Months 8-6)",
    "description": "In this tutorial, learn the comprehensive financial, family, and terminal leave planning phase spanning months 8-6 before ...",
    "publishedAt": "2025-12-01T10:00:20Z",
    "thumbnail": "https://i.ytimg.com/vi/Epb4oNH6Phk/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "Hf0yhwlaoeQ",
    "title": "Separations and Retirement: Skill Development &amp; Professional Growth (Months 10-8)",
    "description": "In this tutorial, learn the comprehensive skill development and professional growth phase spanning months 10-8 before ...",
    "publishedAt": "2025-11-28T10:00:25Z",
    "thumbnail": "https://i.ytimg.com/vi/Hf0yhwlaoeQ/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "E1Ao0Hz7QJk",
    "title": "Separations and Retirement: Foundation Building, Retirement Request, Career Foundation (12-10 Month)",
    "description": "In this tutorial, learn the comprehensive foundation building phase spanning 12-10 months before separation that initiates formal ...",
    "publishedAt": "2025-11-26T10:00:22Z",
    "thumbnail": "https://i.ytimg.com/vi/E1Ao0Hz7QJk/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "eSLW1yPFfsk",
    "title": "Separations and Retirement: Medical, Family &amp; Administrative Preparation (18-12 Months)",
    "description": "In this tutorial, learn the comprehensive medical, family, and administrative preparation phase spanning 18-12 months before ...",
    "publishedAt": "2025-11-24T10:01:05Z",
    "thumbnail": "https://i.ytimg.com/vi/eSLW1yPFfsk/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "fp9x376SfT0",
    "title": "Separations and Retirement: Career, Education &amp; Financial Planning (18-12 Months)",
    "description": "In this tutorial, learn the comprehensive career, education, and financial planning phase spanning 18-12 months before ...",
    "publishedAt": "2025-11-21T10:01:19Z",
    "thumbnail": "https://i.ytimg.com/vi/fp9x376SfT0/default.jpg",
    "channelTitle": "Semper Admin"
  },
  {
    "id": "1FPiMOSriiM",
    "title": "Separations and Retirement: Family, Relocation &amp; Administrative Prep (24-18 Months)",
    "description": "In this tutorial, learn the comprehensive family, relocation, and administrative preparation phase spanning 24-18 months before ...",
    "publishedAt": "2025-11-19T10:00:03Z",
    "thumbnail": "https://i.ytimg.com/vi/1FPiMOSriiM/default.jpg",
    "channelTitle": "Semper Admin"
  }
];

// Export for use in frontend (if using modules) or make globally available
if (typeof module !== 'undefined' && module.exports) {
  module.exports = YOUTUBE_VIDEOS;
}

// Make available globally for browser usage
if (typeof window !== 'undefined') {
  window.YOUTUBE_VIDEOS = YOUTUBE_VIDEOS;
}
