import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import { DisclaimerModal } from "@/components/DisclaimerModal";

// Remove Vercel Analytics since we're deploying to GitHub Pages
// import { Analytics } from '@vercel/analytics/next';

export const metadata: Metadata = {
  title: 'Naval Letter Generator',
  description: 'Generated by Semper Admin',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Roboto:wght@400;500;700&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
      </head>
      <body className="font-body antialiased flex flex-col min-h-screen">
        <main className="flex-1">
          {children}
        </main>
        <DisclaimerModal />
        <Toaster />
        {/* Analytics removed for GitHub Pages deployment */}
      </body>
    </html>
  );
}
