import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import { FeedbackButton } from "@/components/FeedbackButton";
// Remove Vercel Analytics since we're deploying to GitHub Pages
// import { Analytics } from '@vercel/analytics/next';

export const metadata: Metadata = {
  title: 'Naval Letter Generator',
  description: 'Generated by Semper Admin',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Roboto:wght@400;500;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        {children}
        <Toaster />
        <FeedbackButton />
        {/* Analytics removed for GitHub Pages deployment */}
      </body>
    </html>
  );
}
