
export const MILITARY_ACRONYMS: { [key: string]: string } = {
    "DOD": "Department of Defense",
    "SECNAV": "Secretary of the Navy",
    "USMC": "United States Marine Corps",
    "USN": "United States Navy",
    "HQMC": "Headquarters, Marine Corps",
    "MARFORCOM": "Marine Corps Forces Command",
    "MARFORPAC": "Marine Corps Forces, Pacific",
    "I MEF": "I Marine Expeditionary Force",
    "II MEF": "II Marine Expeditionary Force",
    "III MEF": "III Marine Expeditionary Force",
    "TECOM": "Training and Education Command",
    "MCO": "Marine Corps Order",
    "NAVMC": "Navy and Marine Corps Directive",
    "SECNAVINST": "Secretary of the Navy Instruction",
    "OPNAVINST": "Office of the Chief of Naval Operations Instruction",
    "SSIC": "Standard Subject Identification Code",
    "CO": "Commanding Officer",
    "XO": "Executive Officer",
    "OIC": "Officer in Charge",
    "NCOIC": "Noncommissioned Officer in Charge",
    "SgtMaj": "Sergeant Major",
    "1stSgt": "First Sergeant",
    "GySgt": "Gunnery Sergeant",
    "SSgt": "Staff Sergeant",
    "CONUS": "Continental United States",
    "OCONUS": "Outside Continental United States",
    "FOUO": "For Official Use Only",
    "LES": "Leave and Earning Statement",
    "TAD": "Temporary Additional Duty",
    "PCS": "Permanent Change of Station",
    "PCA": "Permanent Change of Assignment",
    "MOL": "Marine Online",
    "NSN": "National Stock Number",
    "CUI": "Controlled Unclassified Information",
};
